-- HD2-Addon: mods/keg/stat_tuner_recon
-- HD2 Stat Tuner - RECON build. Read-only: this file never writes to game memory.
-- It finds the game's data tables in this process, compares a watch-list of values with the
-- offline data it was generated from, and reports everything to
--   %LOCALAPPDATA%\HD2StatTuner\STATUS.txt   (what to send back)
--   %LOCALAPPDATA%\HD2StatTuner\recon.log    (developer log)
-- Requires Bingus Shared Loader (API 1). Runs on LuaJIT (Lua 5.1 syntax only).

local MOD = {
    title = 'HD2 Stat Tuner recon', version = '@@VERSION@@', global = 'HD2StatTunerRecon',
    dir = 'HD2StatTuner', status = 'STATUS.txt', log = 'recon.log',
}
-- Generated by tools/gen_recon_data.py: tables to find (T), values to compare (W),
-- stratagem calibration values (C), name columns (N).
local DATA = [==[
@@DATA@@]==]

if rawget(_G, MOD.global) then return end

-- ---------------------------------------------------------------- tuning
local START_FRAME = 120          -- let the game start before touching anything
local STEP_EVERY = 2             -- work on every 2nd frame only
local FRAME_BUDGET = 0.0015      -- seconds of work per working frame
local CHUNK = 262144             -- bytes per memory read while sweeping
local REST_SECONDS = 20          -- pause between rounds
local MAX_ROUNDS = 180           -- about an hour, then the addon retires
local MAX_SWEEPS = 3             -- full memory sweeps per session
local SWEEP_GAP_SECONDS = 90
local MAX_BLOCK = 0x10000000     -- 256 MB: larger "payload sizes" are not tables
local MAX_MISMATCH_LINES = 40
local ADDRESS_START, ADDRESS_END = 0x10000, 0x7FFFFFFF0000
local LDLD = 0x444C444C          -- 'LDLD' read as a little-endian u32
local MEM_COMMIT, MEM_PRIVATE = 0x1000, 0x20000
local PAGE_READONLY, PAGE_READWRITE = 0x02, 0x04

local state = {
    title = MOD.title, version = MOD.version, phase = 'starting', verdict = 'WAITING',
    frame = 0, round = 0, sweeps = 0, errors = 0, retired = false,
    worst_frame = 0, busy_frames = 0, busy_seconds = 0,
}
rawset(_G, MOD.global, state)

-- ---------------------------------------------------------------- log
local log_lines, log_seen, log_dirty = {}, {}, false
local function log(message)
    message = tostring(message)
    local n = (log_seen[message] or 0) + 1
    log_seen[message] = n
    if n > 3 or #log_lines >= 4000 then return end
    if n == 3 then message = message .. ' (further repeats not logged)' end
    log_lines[#log_lines + 1] = '[frame ' .. state.frame .. '] ' .. message
    log_dirty = true
end

-- Independent IEEE-754 decoder (no FFI type punning; see the float self-test below).
local function bits_to_f32(bits)
    local sign = 1
    if bits >= 2147483648 then sign = -1; bits = bits - 2147483648 end
    local exponent = math.floor(bits / 8388608)
    local mantissa = bits - exponent * 8388608
    if exponent == 255 then
        if mantissa == 0 then return sign * math.huge end
        return 0 / 0
    end
    if exponent == 0 then return sign * mantissa * 2 ^ -149 end
    return sign * (1 + mantissa / 8388608) * 2 ^ (exponent - 127)
end

local function float_selftest()
    local cases = { { 0x3F800000, 1.0 }, { 0x43AF0000, 350.0 }, { 0x42C80000, 100.0 },
                    { 0x3E800000, 0.25 }, { 0xBF000000, -0.5 }, { 0x00000000, 0.0 },
                    { 0x44610000, 900.0 } }
    for _, c in ipairs(cases) do
        if bits_to_f32(c[1]) ~= c[2] then return false end
    end
    return true
end

-- Addresses do not fit a 32-bit %X; print the two halves.
local function hex(n)
    local high = math.floor(n / 4294967296)
    if high > 0 then return string.format('0x%X%08X', high, n - high * 4294967296) end
    return string.format('0x%X', n)
end

-- ---------------------------------------------------------------- windows api (read-only)
local ffi_ok, ffi = pcall(require, 'ffi')
local A = nil   -- the api, built at startup

local function build_api()
    local a = {}
    local cvoid = ffi.typeof('const void *')

    -- Every function is fetched by name and cast to OUR signature, so declarations made by
    -- other addons can never change how we call it. Tests inject their own resolver.
    local resolve = rawget(_G, 'HD2ST_TEST_RESOLVER')
    if type(resolve) ~= 'function' then
        for _, declaration in ipairs({
            'void *GetModuleHandleA(const char *name);',
            'void *LoadLibraryA(const char *name);',
            'void *GetProcAddress(void *module, const char *name);',
        }) do pcall(ffi.cdef, declaration) end
        local k32 = ffi.load('kernel32')
        local get_module = ffi.cast('void *(*)(const char *)', k32.GetModuleHandleA)
        local load_library = ffi.cast('void *(*)(const char *)', k32.LoadLibraryA)
        local get_proc = ffi.cast('void *(*)(void *, const char *)', k32.GetProcAddress)
        resolve = function(dll, name, signature)
            local module = get_module(dll)
            if module == nil then module = load_library(dll) end
            if module == nil then error('cannot load ' .. dll) end
            local address = get_proc(module, name)
            if address == nil then error(name .. ' not found in ' .. dll) end
            return ffi.cast(signature, address)
        end
    end
    local K = 'kernel32.dll'
    local get_process = resolve(K, 'GetCurrentProcess', 'void *(*)(void)')
    local read_memory = resolve(K, 'ReadProcessMemory', 'int (*)(void *, const void *, void *, size_t, size_t *)')
    local virtual_query = resolve(K, 'VirtualQuery', 'size_t (*)(const void *, void *, size_t)')
    local create_directory = resolve(K, 'CreateDirectoryA', 'int (*)(const char *, void *)')
    local get_last_error = resolve(K, 'GetLastError', 'uint32_t (*)(void)')
    local perf_counter = resolve(K, 'QueryPerformanceCounter', 'int (*)(int64_t *)')
    local perf_frequency = resolve(K, 'QueryPerformanceFrequency', 'int (*)(int64_t *)')
    local module_handle = resolve(K, 'GetModuleHandleA', 'void *(*)(const char *)')
    local module_file_name = resolve(K, 'GetModuleFileNameA', 'uint32_t (*)(void *, char *, uint32_t)')
    local create_file = resolve(K, 'CreateFileA',
        'void *(*)(const char *, uint32_t, uint32_t, void *, uint32_t, uint32_t, void *)')
    local read_file = resolve(K, 'ReadFile', 'int (*)(void *, void *, uint32_t, uint32_t *, void *)')
    local file_size = resolve(K, 'GetFileSizeEx', 'int (*)(void *, int64_t *)')
    local close_handle = resolve(K, 'CloseHandle', 'int (*)(void *)')
    local working_set = resolve(K, 'K32QueryWorkingSetEx', 'int (*)(void *, void *, uint32_t)')

    local process = get_process()
    local got = ffi.new('size_t[1]')

    -- timing
    local ticks, frequency = ffi.new('int64_t[1]'), ffi.new('int64_t[1]')
    perf_frequency(frequency)
    local per_second = tonumber(frequency[0])
    if not per_second or per_second <= 0 then error('no performance counter') end
    function a.now()
        perf_counter(ticks)
        return tonumber(ticks[0]) / per_second
    end

    -- memory regions: MEMORY_BASIC_INFORMATION (x64) is 48 bytes; read as raw words
    local mbi = ffi.new('uint64_t[6]')
    local mbi32 = ffi.cast('uint32_t *', mbi)
    -- -> base, size, state, protect, type, allocation base; nil at the end of the address space
    function a.query(address)
        if tonumber(virtual_query(ffi.cast(cvoid, address), mbi, 48)) ~= 48 then return nil end
        local base, size = tonumber(mbi[0]), tonumber(mbi[3])
        if not base or not size or size <= 0 then return nil end
        return base, size, mbi32[8], mbi32[9], mbi32[10], tonumber(mbi[1])
    end

    -- the shared read buffer: CHUNK bytes plus one spare word pair
    a.buffer_size = CHUNK + 16
    a.buffer = ffi.new('uint8_t[?]', a.buffer_size)
    a.words = ffi.cast('uint32_t *', a.buffer)
    a.buffer_address = tonumber(ffi.cast('uintptr_t', a.buffer))

    -- Reads `size` bytes into the shared buffer; true only when all of them were read.
    function a.read(address, size)
        if size <= 0 or size > a.buffer_size then return false end
        if read_memory(process, ffi.cast(cvoid, address), a.buffer, size, got) == 0 then return false end
        return tonumber(got[0]) == size
    end

    -- Which of `count` pages (at most 65) from the page-aligned `address` are present in memory.
    -- Reading a page that is committed but was never touched would make Windows allocate it,
    -- so the sweep only reads pages that are already there. -> array of booleans, or nil.
    local pages = ffi.new('uint64_t[130]')
    local present = {}
    function a.present(address, count)
        for k = 0, count - 1 do pages[2 * k], pages[2 * k + 1] = address + k * 4096, 0 end
        if working_set(process, pages, count * 16) == 0 then return nil end
        for k = 0, count - 1 do present[k + 1] = tonumber(pages[2 * k + 1] % 2) == 1 end
        present[count + 1] = false
        return present
    end

    local cell = ffi.new('uint32_t[2]')
    function a.u32(address)
        if read_memory(process, ffi.cast(cvoid, address), cell, 4, got) == 0 then return nil end
        if tonumber(got[0]) ~= 4 then return nil end
        return tonumber(cell[0])
    end
    function a.u8(address)
        local byte = ffi.cast('uint8_t *', cell)
        if read_memory(process, ffi.cast(cvoid, address), cell, 1, got) == 0 then return nil end
        if tonumber(got[0]) ~= 1 then return nil end
        return byte[0]
    end
    -- a 64-bit value as a Lua number (exact below 2^53: enough for user-space addresses and counts)
    function a.u64(address)
        if read_memory(process, ffi.cast(cvoid, address), cell, 8, got) == 0 then return nil end
        if tonumber(got[0]) ~= 8 then return nil end
        return tonumber(cell[0]) + tonumber(cell[1]) * 4294967296, tonumber(cell[0]), tonumber(cell[1])
    end

    function a.mkdir(path)
        return create_directory(path, nil) ~= 0 or get_last_error() == 183   -- already exists
    end

    -- modules and files (build identity)
    function a.module(name)   -- nil name: the game executable
        local handle = module_handle(name)
        if handle == nil then return nil end
        local path_buffer = ffi.new('char[1024]')
        local length = module_file_name(handle, path_buffer, 1024)
        return tonumber(ffi.cast('uintptr_t', handle)), length > 0 and ffi.string(path_buffer, length) or nil
    end

    function a.open(path)
        local handle = create_file(path, 0x80000000, 7, nil, 3, 0x08000000, nil)
        if handle == nil or tonumber(ffi.cast('intptr_t', handle)) == -1 then return nil end
        local size = ffi.new('int64_t[1]')
        if file_size(handle, size) == 0 then close_handle(handle); return nil end
        return handle, tonumber(size[0])
    end
    local file_got = ffi.new('uint32_t[1]')
    -- next piece of the file into the shared buffer -> bytes read (0 at the end), nil on error
    function a.read_file(handle)
        if read_file(handle, a.buffer, CHUNK, file_got, nil) == 0 then return nil end
        return tonumber(file_got[0])
    end
    function a.close(handle) close_handle(handle) end

    -- SHA-256 through Windows CNG (bcrypt.dll)
    local B = 'bcrypt.dll'
    local open_algorithm = resolve(B, 'BCryptOpenAlgorithmProvider',
        'int32_t (*)(void **, const uint16_t *, const uint16_t *, uint32_t)')
    local close_algorithm = resolve(B, 'BCryptCloseAlgorithmProvider', 'int32_t (*)(void *, uint32_t)')
    local create_hash = resolve(B, 'BCryptCreateHash',
        'int32_t (*)(void *, void **, uint8_t *, uint32_t, uint8_t *, uint32_t, uint32_t)')
    local hash_data = resolve(B, 'BCryptHashData', 'int32_t (*)(void *, uint8_t *, uint32_t, uint32_t)')
    local finish_hash = resolve(B, 'BCryptFinishHash', 'int32_t (*)(void *, uint8_t *, uint32_t, uint32_t)')
    local destroy_hash = resolve(B, 'BCryptDestroyHash', 'int32_t (*)(void *)')
    local sha256_name = ffi.new('uint16_t[7]', { 83, 72, 65, 50, 53, 54, 0 })   -- L"SHA256"

    function a.sha256_begin()
        local algorithm, hash = ffi.new('void *[1]'), ffi.new('void *[1]')
        if open_algorithm(algorithm, sha256_name, nil, 0) ~= 0 then return nil end
        if create_hash(algorithm[0], hash, nil, 0, nil, 0, 0) ~= 0 then
            close_algorithm(algorithm[0], 0)
            return nil
        end
        return { algorithm = algorithm[0], hash = hash[0] }
    end
    function a.sha256_update(context, size)   -- hashes the first `size` bytes of the shared buffer
        return hash_data(context.hash, a.buffer, size, 0) == 0
    end
    function a.sha256_finish(context)
        local digest = ffi.new('uint8_t[32]')
        local ok = finish_hash(context.hash, digest, 32, 0) == 0
        destroy_hash(context.hash)
        close_algorithm(context.algorithm, 0)
        if not ok then return nil end
        local parts = {}
        for i = 0, 31 do parts[i + 1] = string.format('%02X', digest[i]) end
        return table.concat(parts)
    end

    return a
end

-- ---------------------------------------------------------------- files
local out_dir = nil
local function ensure_out_dir()
    if out_dir then return out_dir end
    local base = os.getenv('LOCALAPPDATA')
    if not base or base == '' then return nil end
    local dir = base .. '\\' .. MOD.dir
    if A then pcall(A.mkdir, dir) end
    out_dir = dir
    return dir
end

-- Writes into our own folder; when that is impossible (it could not be created), into the
-- loader's log folder, which exists whenever the loader runs.
local function write_file(name, text)
    local ok = pcall(function()
        local base = os.getenv('LOCALAPPDATA')
        local dir = ensure_out_dir()
        local handle = dir and io.open(dir .. '\\' .. name, 'wb')
        if not handle and base then
            handle = io.open(base .. '\\CowboyBingus\\Helldivers2\\Logs\\' .. MOD.dir .. '-' .. name, 'wb')
        end
        if not handle then return end
        handle:write(text)
        handle:close()
    end)
    return ok
end

local function flush_log()
    log_dirty = false
    write_file(MOD.log, MOD.title .. ' v' .. MOD.version .. '\r\n'
        .. 'phase: ' .. state.phase .. '   round: ' .. state.round .. '   errors: ' .. state.errors .. '\r\n\r\n'
        .. table.concat(log_lines, '\r\n') .. '\r\n')
end

-- ---------------------------------------------------------------- cooperative scheduling
-- All long work runs inside one coroutine; pause() gives the frame back when the budget is spent.
local deadline = 0
local function pause()
    if A.now() >= deadline then coroutine.yield() end
end

-- ---------------------------------------------------------------- generated data
local SPECS, SPEC_BY_TYPE, SPEC_ORDER = {}, {}, {}   -- name -> spec; type hash -> spec; names in order
local WATCH = {}                                      -- table name -> list of watch entries
local CALIBRATION = {}                                -- stratagem id -> { uses, cooldown }
local watch_total = 0

local data_parsed = false
local function parse_data()
    if data_parsed then return end
    data_parsed = true
    local count = 0
    for line in DATA:gmatch('[^\n]+') do
        local kind = line:sub(1, 1)
        local f = {}
        for field in (line .. '|'):gmatch('([^|]*)|') do f[#f + 1] = field end
        if kind == 'T' then
            local spec = { name = f[2], type = tonumber(f[3], 16), shape = f[4],
                           stride = tonumber(f[5]), id_at = tonumber(f[6]), copies = {} }
            SPECS[spec.name], SPEC_BY_TYPE[spec.type] = spec, spec
            SPEC_ORDER[#SPEC_ORDER + 1] = spec.name
        elseif kind == 'W' then
            local list = WATCH[f[2]]
            if not list then list = {}; WATCH[f[2]] = list end
            list[#list + 1] = { key = f[3], offset = tonumber(f[4]), storage = f[5],
                                expected = tonumber(f[6]), label = f[7] }
            watch_total = watch_total + 1
        elseif kind == 'C' then
            CALIBRATION[tonumber(f[2])] = { uses = tonumber(f[3]), cooldown = tonumber(f[4]) }
        elseif kind == 'N' then
            if SPECS[f[2]] then SPECS[f[2]].name_at = tonumber(f[3]) end
        end
        count = count + 1
        if count % 200 == 0 then pause() end
    end
    log('data: ' .. #SPEC_ORDER .. ' tables, ' .. watch_total .. ' watch values')
end

-- ---------------------------------------------------------------- census
-- Every LDLD block found: address -> { address, type, size, origin }.
local census = { blocks = {}, list = {}, kept = {} }
local scan = { regions = 0, readable = 0, bytes = 0, read_failures = 0, slowest_query = 0,
               seconds = 0, sweep_bytes = 0, skipped_pages = 0 }

local function in_own_buffer(address)
    return address >= A.buffer_address and address < A.buffer_address + A.buffer_size
end

-- Registers the block at `address` when its header is a plausible LDLD header.
local function register(address, origin)
    local known = census.blocks[address]
    if known then return known end
    if in_own_buffer(address) then return nil end
    local magic = A.u32(address)
    if magic ~= LDLD or A.u32(address + 4) ~= 1 then return nil end
    local kind, size = A.u32(address + 8), A.u32(address + 12)
    if not kind or kind == 0 or not size or size == 0 or size > MAX_BLOCK then return nil end
    local block = { address = address, type = kind, size = size, origin = origin }
    census.blocks[address] = block
    census.list[#census.list + 1] = block
    return block
end

-- Blocks are often packed back to back: follow the chain from one header to the next.
local function walk(address, origin)
    local steps = 0
    while steps < 200000 do
        local block = register(address, steps == 0 and origin or 'chain')
        if not block then return end
        steps = steps + 1
        local after = block.address + 24 + block.size
        local next_address = nil
        for skip = 0, 16, 4 do
            if A.u32(after + skip) == LDLD and A.u32(after + skip + 4) == 1 then
                next_address = after + skip
                break
            end
        end
        if not next_address or census.blocks[next_address] then return end
        address = next_address
        pause()
    end
end

-- The hot loop: positions (in words) of 'LDLD', 1 in the shared buffer.
local function find_headers(words, count, hits)
    local found = 0
    for i = 0, count - 2 do
        if words[i] == LDLD and words[i + 1] == 1 then
            found = found + 1
            hits[found] = i
        end
    end
    return found
end

local hits = {}
local function scan_run(address, bytes)
    if not A.read(address, bytes) then
        scan.read_failures = scan.read_failures + 1
        return
    end
    scan.sweep_bytes = scan.sweep_bytes + bytes
    local found = find_headers(A.words, bytes / 4, hits)
    for k = 1, found do
        local at = address + hits[k] * 4
        if not census.blocks[at] then
            local ok, why = pcall(walk, at, 'sweep')
            if not ok then log('walk failed at ' .. hex(at) .. ': ' .. tostring(why)) end
        end
    end
end

-- Sweeps one region, CHUNK bytes at a time, reading only the pages present in memory. Each read
-- takes 4 bytes of the following page when that page is present, so a header on a boundary is seen.
local function sweep_region(base, size)
    local offset = 0
    while offset < size do
        local span = math.min(CHUNK, size - offset)
        local count = math.ceil(span / 4096)
        local extra = (offset + span < size) and 1 or 0
        local present = A.present(base + offset, count + extra)
        if present then
            local k = 1
            while k <= count do
                if present[k] then
                    local last = k
                    while last < count and present[last + 1] do last = last + 1 end
                    local bytes = (last - k + 1) * 4096
                    if last + 1 <= count + extra and present[last + 1] then bytes = bytes + 4 end
                    scan_run(base + offset + (k - 1) * 4096, bytes)
                    k = last + 1
                else
                    scan.skipped_pages = scan.skipped_pages + 1
                    k = k + 1
                end
            end
        else
            scan.read_failures = scan.read_failures + 1
        end
        offset = offset + CHUNK
        pause()
    end
end

-- One pass over the address space. mode 'fast': only the first bytes of each allocation;
-- mode 'sweep': every readable, committed, private page that is present in memory.
local function enumerate(mode)
    local started = A.now()
    census.blocks, census.list = {}, {}
    scan.regions, scan.readable, scan.read_failures, scan.sweep_bytes = 0, 0, 0, 0
    if mode == 'sweep' then scan.skipped_pages = 0 end
    -- blocks a sweep found away from an allocation start are checked again directly
    for address, origin in pairs(census.kept) do
        if not register(address, origin) then census.kept[address] = nil end
    end
    local cursor = ADDRESS_START
    while cursor < ADDRESS_END do
        local t0 = A.now()
        local base, size, mem_state, protect, mem_type, allocation = A.query(cursor)
        local cost = A.now() - t0
        if cost > scan.slowest_query then scan.slowest_query = cost end
        if not base then break end
        scan.regions = scan.regions + 1
        -- the tables are heap data: committed, readable, private memory only (never file
        -- mappings or module images)
        if mem_state == MEM_COMMIT and mem_type == MEM_PRIVATE
            and (protect == PAGE_READWRITE or protect == PAGE_READONLY) then
            scan.readable = scan.readable + 1
            -- both modes: a table at the very start of an allocation (and the chain behind it)
            if base == allocation and (A.present(base, 1) or {})[1] then
                if A.u32(base) == LDLD and A.u32(base + 4) == 1 then
                    walk(base, 'allocation+0')
                elseif A.u32(base + 4) == LDLD and A.u32(base + 8) == 1 then
                    walk(base + 4, 'allocation+4')
                end
            end
            -- sweep: everything else in the region (blocks already known keep their origin)
            if mode == 'sweep' then sweep_region(base, size) end
        end
        local next_cursor = base + size
        if next_cursor <= cursor then next_cursor = cursor + 4096 end
        cursor = next_cursor
        pause()
    end
    if mode == 'sweep' then
        for _, block in ipairs(census.list) do
            if block.origin == 'sweep' then census.kept[block.address] = 'sweep' end
        end
        scan.bytes = scan.sweep_bytes
    end
    scan.seconds = A.now() - started
end

-- ---------------------------------------------------------------- table parsing
-- Keyed table: buckets of (u64 entity, u32 record index, u32 0), twice as many as entities,
-- then fixed-size records. The bucket count is derived, never assumed.
local function parse_keyed(block, spec)
    local payload, size, stride = block.address + 24, block.size, spec.stride
    local limit = math.floor(size / (16 + stride / 2)) + 4   -- more buckets cannot fit
    local count, live, top, fits = 0, 0, -1, {}
    local offset, stop = 0, false
    while not stop and offset + 16 <= size and count <= limit do
        local want = math.min(8192, size - offset)
        want = want - want % 16
        if want < 16 or not A.read(payload + offset, want) then break end
        local w = A.words
        for k = 0, want / 16 - 1 do
            local lo, hi, index, pad = w[k * 4], w[k * 4 + 1], w[k * 4 + 2], w[k * 4 + 3]
            if pad ~= 0 or index > 1000000 or count > limit then stop = true break end
            count = count + 1
            if lo ~= 0 or hi ~= 0 then
                live = live + 1
                if index > top then top = index end
            end
            local rest = size - count * 16
            if count == 2 * live and rest > 0 and rest % stride < 8 then
                local records = (rest - rest % stride) / stride
                if records > top and records <= live + 2 then
                    fits[#fits + 1] = { buckets = count, records = records, slack = rest % stride }
                end
            end
        end
        offset = offset + want
        pause()
    end
    if #fits ~= 1 then return nil, #fits .. ' bucket layouts fit (need exactly 1)' end
    local fit = fits[1]
    local index, entries = {}, 0
    offset = 0
    while offset < fit.buckets * 16 do
        local want = math.min(8192, fit.buckets * 16 - offset)
        if not A.read(payload + offset, want) then return nil, 'bucket array unreadable' end
        local w = A.words
        for k = 0, want / 16 - 1 do
            local lo, hi = w[k * 4], w[k * 4 + 1]
            if lo ~= 0 or hi ~= 0 then
                local key = string.format('%08X%08X', hi, lo)
                if index[key] == nil then
                    index[key] = w[k * 4 + 2]
                    entries = entries + 1
                end
            end
        end
        offset = offset + want
        pause()
    end
    return { shape = 'K', records_at = payload + fit.buckets * 16, stride = stride, index = index,
             entries = entries, count = fit.records, buckets = fit.buckets, slack = fit.slack }
end

-- Row table: DLArray (u64 pointer-or-offset, u64 count), then rows carrying a u32 id.
local function parse_rows(block, spec)
    local payload, size, stride = block.address + 24, block.size, spec.stride
    local pointer = A.u64(payload)
    local count = A.u64(payload + 8)
    if not pointer or not count then return nil, 'array head unreadable' end
    local rows_at, form
    if pointer < size then
        rows_at, form = payload + pointer, 'relative offset ' .. pointer
    elseif pointer >= payload and pointer < payload + size then
        rows_at, form = pointer, 'absolute pointer, inside the block (+' .. (pointer - payload) .. ')'
    else
        rows_at, form = pointer, 'absolute pointer, OUTSIDE the block'
    end
    if count == 0 or count * stride > MAX_BLOCK then return nil, 'implausible row count ' .. count end
    if rows_at >= payload and rows_at < payload + size and (rows_at - payload) + count * stride > size then
        return nil, 'rows do not fit: count ' .. count .. ' stride ' .. stride .. ' size ' .. size
    end
    local index, entries, duplicates = {}, 0, 0
    local per_read = math.max(1, math.floor(CHUNK / stride))
    local row = 0
    while row < count do
        local n = math.min(per_read, count - row)
        if not A.read(rows_at + row * stride, n * stride) then return nil, 'rows unreadable at row ' .. row end
        local bytes = A.buffer
        for k = 0, n - 1 do
            local at = k * stride + spec.id_at
            local id = bytes[at] + bytes[at + 1] * 256 + bytes[at + 2] * 65536 + bytes[at + 3] * 16777216
            if index[id] == nil then
                index[id] = row + k
                entries = entries + 1
            else
                duplicates = duplicates + 1
            end
        end
        row = row + n
        pause()
    end
    return { shape = 'R', records_at = rows_at, stride = stride, index = index, entries = entries,
             count = count, form = form, duplicates = duplicates,
             tail = size - 16 - count * stride, relative = pointer < size, payload = payload }
end

local function read_value(address, storage)
    if storage == 'u8' then return A.u8(address) end
    local bits = A.u32(address)
    if bits == nil then return nil end
    if storage == 'f32' then return bits_to_f32(bits) end
    if storage == 'i32' and bits >= 2147483648 then return bits - 4294967296 end
    return bits
end

local function same(storage, live, expected)
    if live == nil or live ~= live then return false end
    if storage == 'f32' then
        return math.abs(live - expected) <= 0.0001 * math.max(1, math.abs(expected))
    end
    return live == expected
end

local function run_watches(spec, parsed, result)
    local list = WATCH[spec.name]
    if not list then return end
    local matched, differing, missing, unreadable = 0, 0, 0, 0
    result.mismatches, result.missing = {}, {}
    for n, w in ipairs(list) do
        local key = w.key
        if parsed.shape == 'R' then key = tonumber(key) end
        local record = parsed.index[key]
        if record == nil then
            missing = missing + 1
            if #result.missing < 12 then result.missing[#result.missing + 1] = w.label .. ' (' .. w.key .. ')' end
        else
            local live = read_value(parsed.records_at + record * parsed.stride + w.offset, w.storage)
            if live == nil then
                unreadable = unreadable + 1
            elseif same(w.storage, live, w.expected) then
                matched = matched + 1
            else
                differing = differing + 1
                if #result.mismatches < MAX_MISMATCH_LINES then
                    result.mismatches[#result.mismatches + 1] = string.format(
                        '%s  key %s +%d %s  offline %s  live %s', w.label, w.key, w.offset, w.storage,
                        tostring(w.expected), tostring(live))
                end
            end
        end
        if n % 64 == 0 then pause() end
    end
    result.watch = { total = #list, matched = matched, differing = differing,
                     missing = missing, unreadable = unreadable }
end

-- A C string behind a pointer field (relative tables keep offsets instead of pointers).
local function read_name(parsed, address)
    local pointer = A.u64(address)
    if not pointer or pointer == 0 then return '' end
    if parsed.relative then pointer = parsed.payload + pointer end
    if not A.read(pointer, 64) then return '?' end
    local chars = {}
    for i = 0, 63 do
        local c = A.buffer[i]
        if c == 0 then break end
        chars[#chars + 1] = (c >= 32 and c < 127) and string.char(c) or '?'
    end
    return table.concat(chars)
end

local function hex_bytes(address, size)
    if not A.read(address, size) then return '(unreadable)' end
    local parts = {}
    for i = 0, size - 1 do parts[#parts + 1] = string.format('%02X', A.buffer[i]) end
    return table.concat(parts)
end

-- Status effects: id = debug name for every row; raw bytes of the acid / gas / storm rows.
local function list_status_effects(spec, parsed, result)
    local lines, dumps = {}, {}
    local ids = {}
    for id, row in pairs(parsed.index) do ids[#ids + 1] = { id = id, row = row } end
    table.sort(ids, function(x, y) return x.id < y.id end)
    for _, entry in ipairs(ids) do
        local at = parsed.records_at + entry.row * parsed.stride
        local name = read_name(parsed, at + spec.name_at)
        lines[#lines + 1] = entry.id .. '=' .. name
        local lower = name:lower()
        if lower:find('acid', 1, true) or lower:find('gas', 1, true) or lower:find('storm', 1, true) then
            dumps[#dumps + 1] = entry.id .. ' ' .. name .. ': ' .. hex_bytes(at, parsed.stride)
        end
        pause()
    end
    result.names, result.dumps = lines, dumps
end

-- Stratagems: list every row, and vote which float offset holds the cooldown.
local function list_stratagems(spec, parsed, result)
    local lines, votes, uses_ok, known = {}, {}, 0, 0
    for offset = 84, 108, 4 do votes[offset] = 0 end
    local ids = {}
    for id, row in pairs(parsed.index) do ids[#ids + 1] = { id = id, row = row } end
    table.sort(ids, function(x, y) return x.row < y.row end)
    for _, entry in ipairs(ids) do
        local at = parsed.records_at + entry.row * parsed.stride
        local name = read_name(parsed, at + spec.name_at)
        local uses = A.u32(at + 80)
        local floats = {}
        for offset = 84, 108, 4 do
            local bits = A.u32(at + offset)
            floats[#floats + 1] = bits and string.format('%g', bits_to_f32(bits)) or '?'
        end
        local expected = CALIBRATION[entry.id]
        if expected then
            known = known + 1
            if uses == expected.uses then uses_ok = uses_ok + 1 end
            for offset = 84, 108, 4 do
                local bits = A.u32(at + offset)
                if bits and same('f32', bits_to_f32(bits), expected.cooldown) then
                    votes[offset] = votes[offset] + 1
                end
            end
        end
        lines[#lines + 1] = string.format('%u "%s" uses@80=%s f32@84..108=[%s]%s', entry.id, name,
            tostring(uses), table.concat(floats, ' '),
            expected and (' snapshot cooldown ' .. tostring(expected.cooldown)) or ' (not in snapshot)')
        pause()
    end
    result.stratagems = lines
    result.calibration = { known = known, uses_ok = uses_ok, votes = votes }
end

-- Delta storage: five arrays (pointer, count); which component indices the deltas touch.
local function inspect_deltas(block, result)
    local payload, size = block.address + 24, block.size
    local arrays = {}
    for k = 0, 4 do
        local pointer = A.u64(payload + k * 16)
        local count = A.u64(payload + k * 16 + 8)
        if not pointer or not count then return nil, 'array heads unreadable' end
        local relative = pointer < size
        arrays[k] = { at = relative and payload + pointer or pointer, count = count, relative = relative }
    end
    result.form = (arrays[0].relative and 'relative offsets' or 'absolute pointers')
    result.arrays = string.format('resources %d, settings %d, components %d, deltas %d, data bytes %d',
        arrays[0].count, arrays[1].count, arrays[2].count, arrays[3].count, arrays[4].count)
    local components, deltas = arrays[2], arrays[3]
    if components.count > 200000 or deltas.count > 2000000 then return nil, 'implausible counts' end
    local per_index = {}
    for c = 0, components.count - 1 do
        local at = components.at + c * 12
        local index, first, count = A.u32(at), A.u32(at + 4), A.u32(at + 8)
        if not index or not first or not count then return nil, 'component array unreadable' end
        local entry = per_index[index]
        if not entry then entry = { index = index, deltas = 0, offsets = {} }; per_index[index] = entry end
        entry.deltas = entry.deltas + count
        for d = first, math.min(first + count, deltas.count) - 1 do
            local offset = A.u32(deltas.at + d * 12)
            if offset then entry.offsets[offset] = (entry.offsets[offset] or 0) + 1 end
        end
        pause()
    end
    local ordered = {}
    for _, entry in pairs(per_index) do ordered[#ordered + 1] = entry end
    table.sort(ordered, function(x, y) return x.deltas > y.deltas end)
    local lines = {}
    for n = 1, math.min(#ordered, 12) do
        local entry, offsets = ordered[n], {}
        for offset, count in pairs(entry.offsets) do offsets[#offsets + 1] = { offset, count } end
        table.sort(offsets, function(x, y) return x[2] > y[2] or (x[2] == y[2] and x[1] < y[1]) end)
        local top = {}
        for k = 1, math.min(#offsets, 6) do top[k] = '+' .. offsets[k][1] .. 'x' .. offsets[k][2] end
        lines[n] = string.format('component %d: %d deltas, top offsets %s', entry.index, entry.deltas,
                                 table.concat(top, ' '))
    end
    result.components = lines
    return true
end

-- ---------------------------------------------------------------- analysis
local analyzed = {}   -- 'address:type:size' -> result (kept between rounds)

local function analyze_block(block, spec)
    local result = { address = block.address, size = block.size, origin = block.origin }
    local parsed, why
    if spec.shape == 'K' then
        parsed, why = parse_keyed(block, spec)
    elseif spec.shape == 'R' then
        parsed, why = parse_rows(block, spec)
    elseif spec.shape == 'D' then
        local ok, reason = inspect_deltas(block, result)
        if not ok then result.problem = reason end
        return result
    else
        return result   -- single-record blocks are only counted
    end
    if not parsed then
        result.problem = why
        result.head = hex_bytes(block.address + 24, math.min(64, block.size))
        return result
    end
    result.count, result.entries, result.form = parsed.count, parsed.entries, parsed.form
    result.buckets, result.slack, result.tail, result.duplicates = parsed.buckets, parsed.slack, parsed.tail,
        parsed.duplicates
    run_watches(spec, parsed, result)
    if spec.name == 'StatusEffectSettings' and spec.name_at then list_status_effects(spec, parsed, result) end
    if spec.name == 'StratagemSettings' and spec.name_at then list_stratagems(spec, parsed, result) end
    return result
end

local function analyze()
    for _, name in ipairs(SPEC_ORDER) do SPECS[name].copies = {} end
    for _, block in ipairs(census.list) do
        local spec = SPEC_BY_TYPE[block.type]
        if spec then
            local key = block.address .. ':' .. block.type .. ':' .. block.size
            local result = analyzed[key]
            if not result then
                local ok, value = pcall(analyze_block, block, spec)
                if ok then
                    result = value
                else
                    state.errors = state.errors + 1
                    log('analysis of ' .. spec.name .. ' at ' .. hex(block.address) .. ' failed: ' .. tostring(value))
                    result = { address = block.address, size = block.size, origin = block.origin,
                               problem = 'error: ' .. tostring(value) }
                end
                analyzed[key] = result
                state.first_seen = state.first_seen or {}
                state.first_seen[key] = state.round
            end
            result.origin = block.origin
            spec.copies[#spec.copies + 1] = result
        end
        pause()
    end
    -- stable order: copies at allocation starts / in chains first, then by address
    for _, name in ipairs(SPEC_ORDER) do
        table.sort(SPECS[name].copies, function(x, y)
            local sx, sy = x.origin == 'sweep', y.origin == 'sweep'
            if sx ~= sy then return sy end
            return x.address < y.address
        end)
    end
end

-- ---------------------------------------------------------------- build identity
local build = { modules = {} }

local function identify_module(name)
    local info = { name = name or '(game executable)' }
    local base, path = A.module(name)
    if not base then info.note = 'not loaded'; return info end
    info.base, info.path = base, path
    -- PE header, read from the loaded image
    local pe = A.u32(base + 0x3C)
    if pe and pe < 0x1000 and A.u32(base + pe) == 0x00004550 then
        info.timestamp = A.u32(base + pe + 8)
        info.image_size = A.u32(base + pe + 80)
        info.checksum = A.u32(base + pe + 88)
    end
    if path then
        local handle, size = A.open(path)
        if not handle then
            info.note = 'file could not be opened'
        else
            info.file_size = size
            local context = A.sha256_begin()
            if not context then
                info.note = 'SHA-256 unavailable'
            else
                local total, ok = 0, true
                while true do
                    local n = A.read_file(handle)
                    if n == nil then ok = false break end
                    if n == 0 then break end
                    if not A.sha256_update(context, n) then ok = false break end
                    total = total + n
                    pause()
                end
                local digest = A.sha256_finish(context)
                if ok and digest and total == size then info.sha256 = digest
                else info.note = 'hashing failed after ' .. total .. ' bytes' end
            end
            A.close(handle)
        end
    end
    return info
end

local function identify_build()
    for _, name in ipairs({ false, 'game.dll' }) do
        local ok, info = pcall(identify_module, name or nil)
        if ok then build.modules[#build.modules + 1] = info
        else log('build identity (' .. tostring(name) .. '): ' .. tostring(info)) end
    end
    build.done = true
end

-- ---------------------------------------------------------------- STATUS
local function loader_line()
    local loader = rawget(_G, 'CowboyBingusModLoader')
    if type(loader) ~= 'table' then return 'loader: CowboyBingusModLoader global not found' end
    return 'loader: api=' .. tostring(loader.api) .. ' version=' .. tostring(loader.version)
end

local function build_status()
    local L = {}
    local function add(text) L[#L + 1] = text end
    local found, wanted, core_missing = 0, 0, {}
    local w_total, w_matched, w_differing, w_missing = 0, 0, 0, 0
    for _, name in ipairs(SPEC_ORDER) do
        local spec = SPECS[name]
        wanted = wanted + 1
        if #spec.copies > 0 then found = found + 1 else core_missing[#core_missing + 1] = name end
        local first = spec.copies[1]
        if first and first.watch then
            w_total = w_total + first.watch.total
            w_matched = w_matched + first.watch.matched
            w_differing = w_differing + first.watch.differing
            w_missing = w_missing + first.watch.missing
        elseif WATCH[name] then
            w_total = w_total + #WATCH[name]
            w_missing = w_missing + #WATCH[name]
        end
    end
    local verdict
    if state.phase == 'gave_up' then
        verdict = 'FAILED - ' .. tostring(state.failure)
    elseif state.round == 0 or wanted == 0 then
        verdict = 'WAITING - first scan not finished yet (keep the game running)'
    elseif found == wanted and w_total > 0 and w_matched == w_total then
        verdict = 'OK - all ' .. wanted .. ' tables found, all ' .. w_total .. ' watched values match the offline data'
    else
        verdict = string.format('PARTIAL - %d of %d tables found; watched values: %d match, %d differ, %d not reachable',
                                found, wanted, w_matched, w_differing, w_missing)
    end
    state.verdict = verdict
    add(verdict)
    add('read-only build: nothing was written to game memory')
    add(MOD.title .. ' v' .. MOD.version)
    add(string.format('phase=%s round=%d sweeps=%d frame=%d errors=%d', state.phase, state.round, state.sweeps,
                      state.frame, state.errors))
    add(loader_line())
    add('self_read=' .. tostring(state.self_read) .. ' watch_values=' .. watch_total)
    add('')
    add('[build]')
    if not build.done then add('not identified yet (done after the first full sweep)') end
    for _, m in ipairs(build.modules) do
        add(string.format('%s: path=%s', m.name, tostring(m.path)))
        add(string.format('  file_size=%s sha256=%s', tostring(m.file_size), tostring(m.sha256)))
        add(string.format('  pe_timestamp=%s image_size=%s pe_checksum=%s%s',
            m.timestamp and hex(m.timestamp) or '?', tostring(m.image_size),
            m.checksum and hex(m.checksum) or '?', m.note and ('  note: ' .. m.note) or ''))
    end
    add('')
    add('[scan]')
    add(string.format('last pass: mode=%s regions=%d readable=%d blocks=%d seconds=%.1f', tostring(state.mode),
        scan.regions, scan.readable, #census.list, scan.seconds))
    add(string.format('sweep: bytes=%.0f read_failures=%d pages_not_in_memory=%d', scan.bytes,
                      scan.read_failures, scan.skipped_pages))
    add(string.format('cost: worst_frame_ms=%.2f busy_frames=%d busy_seconds=%.1f slowest_region_query_ms=%.2f',
        state.worst_frame * 1000, state.busy_frames, state.busy_seconds, scan.slowest_query * 1000))
    add('')
    add('[tables] name type copies | per copy: address payload origin details')
    for _, name in ipairs(SPEC_ORDER) do
        local spec = SPECS[name]
        add(string.format('%s %08X shape=%s stride=%d copies=%d', name, spec.type, spec.shape, spec.stride,
                          #spec.copies))
        local shown = 0
        for _, r in ipairs(spec.copies) do
            shown = shown + 1
            if shown > 12 then add('  ... ' .. (#spec.copies - 12) .. ' more copies') break end
            local detail
            if r.problem then
                detail = 'PROBLEM: ' .. r.problem .. (r.head and (' head=' .. r.head) or '')
            elseif spec.shape == 'K' then
                detail = string.format('records=%d entities=%d buckets=%d slack=%d', r.count or -1, r.entries or -1,
                                       r.buckets or -1, r.slack or -1)
            elseif spec.shape == 'R' then
                detail = string.format('rows=%d ids=%d duplicates=%d tail=%d array=%s', r.count or -1,
                                       r.entries or -1, r.duplicates or -1, r.tail or -1, tostring(r.form))
            elseif spec.shape == 'D' then
                detail = tostring(r.form) .. '; ' .. tostring(r.arrays)
            else
                detail = ''
            end
            if r.watch then
                detail = detail .. string.format(' | watch %d: match %d, differ %d, key missing %d, unreadable %d',
                    r.watch.total, r.watch.matched, r.watch.differing, r.watch.missing, r.watch.unreadable)
            end
            add(string.format('  %s size=%d origin=%s %s', hex(r.address), r.size, tostring(r.origin), detail))
        end
    end
    add('')
    add('[differences] first copy of each table, offline value vs live value')
    local any = false
    for _, name in ipairs(SPEC_ORDER) do
        local first = SPECS[name].copies[1]
        if first and first.mismatches and #first.mismatches > 0 then
            any = true
            for _, line in ipairs(first.mismatches) do add(name .. ': ' .. line) end
            if first.watch.differing > #first.mismatches then
                add(name .. ': ... ' .. (first.watch.differing - #first.mismatches) .. ' more')
            end
        end
        if first and first.missing and #first.missing > 0 then
            any = true
            add(name .. ': keys not in the live table, e.g. ' .. table.concat(first.missing, '; '))
        end
    end
    if not any then add('none') end
    add('')
    add('[stratagems] live rows; cooldown offset votes against the community snapshot')
    local listed = {}
    for _, r in ipairs(SPECS.StratagemSettings and SPECS.StratagemSettings.copies or {}) do
        if r.calibration then
            local votes = {}
            for offset = 84, 108, 4 do votes[#votes + 1] = '+' .. offset .. ':' .. r.calibration.votes[offset] end
            add(string.format('group at %s: known %d, uses@80 match %d, cooldown votes %s', hex(r.address),
                r.calibration.known, r.calibration.uses_ok, table.concat(votes, ' ')))
        end
        for _, line in ipairs(r.stratagems or {}) do
            if not listed[line] then
                listed[line] = true
                add('  ' .. line)
            end
        end
    end
    add('')
    add('[status effects] id=debug name (first copy)')
    local effects = SPECS.StatusEffectSettings and SPECS.StatusEffectSettings.copies[1]
    if effects and effects.names then
        add(table.concat(effects.names, ', '))
        for _, line in ipairs(effects.dumps or {}) do add('raw ' .. line) end
    else
        add('table not found')
    end
    add('')
    add('[attachment deltas]')
    local deltas = SPECS.ComponentEntityDeltaStorage and SPECS.ComponentEntityDeltaStorage.copies[1]
    if deltas and deltas.components then
        for _, line in ipairs(deltas.components) do add(line) end
    else
        add(deltas and ('PROBLEM: ' .. tostring(deltas.problem)) or 'table not found')
    end
    add('')
    add('[census] every LDLD block type seen in the last pass: type count bytes origins')
    local by_type, order = {}, {}
    for _, block in ipairs(census.list) do
        local entry = by_type[block.type]
        if not entry then
            entry = { type = block.type, count = 0, bytes = 0, origins = {} }
            by_type[block.type] = entry
            order[#order + 1] = entry
        end
        entry.count, entry.bytes = entry.count + 1, entry.bytes + block.size
        entry.origins[block.origin] = (entry.origins[block.origin] or 0) + 1
    end
    table.sort(order, function(x, y) return x.bytes > y.bytes end)
    for n, entry in ipairs(order) do
        if n > 400 then add('... ' .. (#order - 400) .. ' more types') break end
        local origins = {}
        for origin, count in pairs(entry.origins) do origins[#origins + 1] = origin .. 'x' .. count end
        table.sort(origins)
        local spec = SPEC_BY_TYPE[entry.type]
        add(string.format('%08X %d %.0f %s%s', entry.type, entry.count, entry.bytes, table.concat(origins, ','),
                          spec and (' ' .. spec.name) or ''))
    end
    add('')
    add('[history] round: frame, mode, blocks, wanted tables found')
    for _, line in ipairs(state.history or {}) do add(line) end
    return table.concat(L, '\r\n') .. '\r\n'
end

local function write_status()
    local ok, text = pcall(build_status)
    if not ok then
        log('status: ' .. tostring(text))
        text = 'FAILED - could not build the status report: ' .. tostring(text) .. '\r\n'
            .. MOD.title .. ' v' .. MOD.version .. '\r\n'
    end
    write_file(MOD.status, text)
    flush_log()
end

-- ---------------------------------------------------------------- rounds
local last_signature, last_sweep_at, resume_at = nil, 0, 0

local function wanted_signature()
    local parts, found = {}, 0
    for _, name in ipairs(SPEC_ORDER) do
        local copies = SPECS[name].copies
        if #copies > 0 then found = found + 1 end
        local addresses = {}
        for _, r in ipairs(copies) do addresses[#addresses + 1] = r.address end
        table.sort(addresses)
        parts[#parts + 1] = table.concat(addresses, ',')
    end
    return table.concat(parts, '|'), found
end

local function rounds()
    parse_data()
    write_status()
    local sweep_next, sweep_wanted = false, false
    while state.round < MAX_ROUNDS do
        state.round = state.round + 1
        local mode = 'fast'
        if state.round == 2 or sweep_next then mode = 'sweep' end
        sweep_next = false
        state.mode, state.phase = mode, 'scanning (' .. mode .. ')'
        enumerate(mode)
        if mode == 'sweep' then
            state.sweeps = state.sweeps + 1
            last_sweep_at = A.now()
        end
        state.phase = 'analyzing'
        analyze()
        local signature, found = wanted_signature()
        state.history = state.history or {}
        if #state.history < 120 then
            state.history[#state.history + 1] = string.format('%d: frame %d, %s, %d blocks, %d of %d tables%s',
                state.round, state.frame, mode, #census.list, found, #SPEC_ORDER,
                signature ~= last_signature and ', copies changed' or '')
        end
        -- the set of copies changed (mission load?): look everywhere again, but not more often
        -- than every SWEEP_GAP_SECONDS and not more than MAX_SWEEPS times
        if last_signature and signature ~= last_signature then sweep_wanted = true end
        if sweep_wanted and state.sweeps < MAX_SWEEPS and A.now() - last_sweep_at >= SWEEP_GAP_SECONDS then
            sweep_next, sweep_wanted = true, false
        end
        local changed = signature ~= last_signature or mode == 'sweep'
        last_signature = signature
        if state.round == 2 and not build.done then
            state.phase = 'identifying the build'
            identify_build()
            changed = true
        end
        state.phase = 'resting'
        if changed or state.round <= 2 or state.round % 15 == 0 then write_status() end
        if not sweep_next then
            resume_at = A.now() + (state.round == 1 and 0 or REST_SECONDS)
            coroutine.yield()
        end
    end
    state.phase = 'done'
    write_status()
end

-- ---------------------------------------------------------------- per frame
local worker = nil

local function retire()
    state.retired = true
    if state.unhook then pcall(state.unhook) end
end

local function tick()
    state.frame = state.frame + 1
    if state.frame < START_FRAME or state.frame % STEP_EVERY ~= 0 then return end
    local now = A.now()
    if now < resume_at then return end
    if not worker then worker = coroutine.create(rounds) end
    deadline = now + FRAME_BUDGET
    local ok, why = coroutine.resume(worker)
    local cost = A.now() - now
    state.busy_frames, state.busy_seconds = state.busy_frames + 1, state.busy_seconds + cost
    if cost > state.worst_frame then state.worst_frame = cost end
    if not ok then
        state.errors = state.errors + 1
        log('round ' .. state.round .. ' failed: ' .. tostring(why))
        worker = nil
        if state.errors >= 5 then
            state.phase, state.failure = 'gave_up', 'too many errors, last: ' .. tostring(why)
            write_status()
            retire()
        else
            resume_at = A.now() + 5
            write_status()
        end
    elseif coroutine.status(worker) == 'dead' then
        log('finished after ' .. state.round .. ' rounds')
        flush_log()
        retire()
    end
end

-- ---------------------------------------------------------------- startup
log(MOD.title .. ' v' .. MOD.version)
-- The API is built first (it only looks functions up) so that even a refusal below can be
-- written to our own folder.
local api_ok, api_failure = pcall(function()
    assert(ffi_ok and ffi, 'LuaJIT FFI is unavailable')
    assert(ffi.abi('64bit'), 'Windows x64 is required')
    A = build_api()
end)
if not api_ok then A = nil end
local ok, failure = pcall(function()
    local loader = rawget(_G, 'CowboyBingusModLoader')
    if type(loader) == 'table' and tonumber(loader.api) and tonumber(loader.api) < 1 then
        error('Bingus Shared Loader is too old (API ' .. tostring(loader.api) .. '); v15 or newer is required', 0)
    end
    if not api_ok then error(tostring(api_failure), 0) end
    if not float_selftest() then error('float decoder self-test failed', 0) end
    if type(rawget(_G, 'update')) ~= 'function' then error('the game update hook is unavailable', 0) end
    -- not fatal: reported in STATUS (a failure here means no memory read can work)
    state.self_read = A.u32(A.buffer_address) ~= nil
end)

if not ok then
    state.phase, state.failure = 'gave_up', tostring(failure)
    log('startup failed: ' .. tostring(failure))
    print('[' .. MOD.global .. '] ' .. tostring(failure))
    write_file(MOD.status, 'FAILED - ' .. tostring(failure) .. '\r\n' .. MOD.title .. ' v' .. MOD.version .. '\r\n')
    flush_log()
    return
end

log('armed; output in ' .. tostring(ensure_out_dir()))
write_file(MOD.status, 'WAITING - the scan starts a few seconds after launch (keep the game running)\r\n'
    .. MOD.title .. ' v' .. MOD.version .. '\r\n')
flush_log()

-- Guarded hook: other addons may wrap `update` after us, so we only restore it when we are
-- still the outermost wrapper; otherwise we stay in the chain and do nothing.
local original_update = update
local my_update
my_update = function(...)
    if not state.retired then
        local tick_ok, why = pcall(tick)
        if not tick_ok then
            state.errors = state.errors + 1
            log('tick: ' .. tostring(why))
            if state.errors >= 20 then retire() end
        end
    end
    return original_update(...)
end
state.unhook = function()
    if rawget(_G, 'update') == my_update then update = original_update end
end
update = my_update
