-- HD2-Addon: mods/keg/stat_tuner
-- HD2 Stat Tuner: changes existing weapon / throwable values in the game's memory from a config
-- file. Files, all in %LOCALAPPDATA%\HD2StatTuner:
--   config.txt    what to change (see docs/CONFIG-FORMAT.md; a template is created on first run)
--   STATUS.txt    what happened: first line is the verdict
--   catalog.txt   every item and stat this build knows, with the game's value and allowed range
--   tuner.log     developer log
-- Requires Bingus Shared Loader (API 1). Runs on LuaJIT (Lua 5.1 syntax only).
--
-- Safety rules this file implements:
--   * nothing is written unless the game executable and game.dll hash to a verified build;
--   * every write is range-checked before, done through the OS (never a raw pointer), read back
--     with an independent decoder, and undone when the config no longer asks for it;
--   * the game keeps its component tables in read-only pages: such a page is made writable for
--     the one 4-byte write and put back to read-only at once (checked);
--   * tables are located by 'LDLD' + version + type hash only; counts and layouts are derived;
--   * all work is sliced: at most FRAME_BUDGET seconds on every STEP_EVERY-th frame.

local MOD = {
    title = 'HD2 Stat Tuner', version = '@@VERSION@@', global = 'HD2StatTuner',
    dir = 'HD2StatTuner', status = 'STATUS.txt', log = 'tuner.log', config = 'config.txt',
    catalog = 'catalog.txt',
}
-- Generated by tools/gen_tuner_data.py: verified builds (V), tables (T), items (I), fields (F),
-- ranges (R), aliases (A).
local DATA = [==[
@@DATA@@]==]

if rawget(_G, MOD.global) then return end

-- ---------------------------------------------------------------- tuning
local START_FRAME = 120          -- let the game start before touching anything
local STEP_EVERY = 2             -- heavy work on every 2nd frame only
local FRAME_BUDGET = 0.001       -- seconds of work per working frame
local RECHECK_SECONDS = 5        -- read back every applied value this often
local RELOAD_DEBOUNCE = 0.75     -- seconds: further presses of the reload key within this time are ignored
local SEARCH_BACKOFF = { 5, 10, 20, 30 }   -- seconds between searches while tables are missing
local DEFAULT_RESCAN_SECONDS = 120          -- look for new copies of patched tables this often
local MAX_BLOCK = 0x10000000
local ADDRESS_START, ADDRESS_END = 0x10000, 0x7FFFFFFF0000
local LDLD = 0x444C444C          -- 'LDLD' read as a little-endian u32
local PAGE_READONLY, PAGE_READWRITE = 0x02, 0x04
local FILE_CHUNK = 262144
local HASH_CHUNK = 65536         -- bytes hashed per step while checking the build

local state = {
    title = MOD.title, version = MOD.version, phase = 'starting', verdict = 'WAITING',
    frame = 0, errors = 0, writes = 0, restores = 0, rewrites = 0, passes = 0, unlocks = 0, left_open = 0,
    reloads = 0,
    worst_frame = 0, busy_frames = 0, busy_seconds = 0,
}
rawset(_G, MOD.global, state)

-- ---------------------------------------------------------------- log
local log_lines, log_seen, log_dirty = {}, {}, false
local function log(message)
    message = tostring(message)
    local n = (log_seen[message] or 0) + 1
    log_seen[message] = n
    if n > 3 or #log_lines >= 4000 then return end
    if n == 3 then message = message .. ' (further repeats not logged)' end
    log_lines[#log_lines + 1] = '[frame ' .. state.frame .. '] ' .. message
    log_dirty = true
end

-- Addresses do not fit a 32-bit %X; print the two halves.
local function hex(n)
    local high = math.floor(n / 4294967296)
    if high > 0 then return string.format('0x%X%08X', high, n - high * 4294967296) end
    return string.format('0x%X', n)
end

local function trim(text) return (text:gsub('^%s+', ''):gsub('%s+$', '')) end

-- ---------------------------------------------------------------- numbers
-- Independent IEEE-754 decoder: read-back checks never share code with the encoder.
local function bits_to_f32(bits)
    local sign = 1
    if bits >= 2147483648 then sign = -1; bits = bits - 2147483648 end
    local exponent = math.floor(bits / 8388608)
    local mantissa = bits - exponent * 8388608
    if exponent == 255 then
        if mantissa == 0 then return sign * math.huge end
        return 0 / 0
    end
    if exponent == 0 then return sign * mantissa * 2 ^ -149 end
    return sign * (1 + mantissa / 8388608) * 2 ^ (exponent - 127)
end

local function close_enough(a, b)
    if a ~= a or b ~= b then return false end
    return math.abs(a - b) <= 0.00001 * math.max(1, math.abs(b))
end

local function same_value(storage, a, b)
    if a == nil or b == nil then return false end
    if storage == 'f32' then return close_enough(a, b) end
    return a == b
end

local function show(value, storage)
    if value == nil then return '?' end
    if storage == 'f32' then
        local text = string.format('%.4f', value):gsub('0+$', ''):gsub('%.$', '')
        return text
    end
    return string.format('%.0f', value)
end

-- ---------------------------------------------------------------- windows api
local ffi_ok, ffi = pcall(require, 'ffi')
local A = nil

local function build_api()
    local a = {}
    local cvoid = ffi.typeof('const void *')
    local void = ffi.typeof('void *')

    -- Every function is fetched by name and cast to OUR signature, so declarations made by
    -- other addons can never change how we call it. Tests inject their own resolver.
    local resolve = rawget(_G, 'HD2ST_TEST_RESOLVER')
    if type(resolve) ~= 'function' then
        for _, declaration in ipairs({
            'void *GetModuleHandleA(const char *name);',
            'void *LoadLibraryA(const char *name);',
            'void *GetProcAddress(void *module, const char *name);',
        }) do pcall(ffi.cdef, declaration) end
        local k32 = ffi.load('kernel32')
        local get_module = ffi.cast('void *(*)(const char *)', k32.GetModuleHandleA)
        local load_library = ffi.cast('void *(*)(const char *)', k32.LoadLibraryA)
        local get_proc = ffi.cast('void *(*)(void *, const char *)', k32.GetProcAddress)
        resolve = function(dll, name, signature)
            local module = get_module(dll)
            if module == nil then module = load_library(dll) end
            if module == nil then error('cannot load ' .. dll) end
            local address = get_proc(module, name)
            if address == nil then error(name .. ' not found in ' .. dll) end
            return ffi.cast(signature, address)
        end
    end
    local K = 'kernel32.dll'
    local get_process = resolve(K, 'GetCurrentProcess', 'void *(*)(void)')
    local get_process_id = resolve(K, 'GetCurrentProcessId', 'uint32_t (*)(void)')
    local read_memory = resolve(K, 'ReadProcessMemory', 'int (*)(void *, const void *, void *, size_t, size_t *)')
    local write_memory = resolve(K, 'WriteProcessMemory', 'int (*)(void *, void *, const void *, size_t, size_t *)')
    local virtual_query = resolve(K, 'VirtualQuery', 'size_t (*)(const void *, void *, size_t)')
    local virtual_protect = resolve(K, 'VirtualProtect', 'int (*)(void *, size_t, uint32_t, uint32_t *)')
    local working_set = resolve(K, 'K32QueryWorkingSetEx', 'int (*)(void *, void *, uint32_t)')
    local create_directory = resolve(K, 'CreateDirectoryA', 'int (*)(const char *, void *)')
    local get_last_error = resolve(K, 'GetLastError', 'uint32_t (*)(void)')
    local perf_counter = resolve(K, 'QueryPerformanceCounter', 'int (*)(int64_t *)')
    local perf_frequency = resolve(K, 'QueryPerformanceFrequency', 'int (*)(int64_t *)')
    local module_handle = resolve(K, 'GetModuleHandleA', 'void *(*)(const char *)')
    local module_file_name = resolve(K, 'GetModuleFileNameA', 'uint32_t (*)(void *, char *, uint32_t)')
    local create_file = resolve(K, 'CreateFileA',
        'void *(*)(const char *, uint32_t, uint32_t, void *, uint32_t, uint32_t, void *)')
    local read_file = resolve(K, 'ReadFile', 'int (*)(void *, void *, uint32_t, uint32_t *, void *)')
    local file_size = resolve(K, 'GetFileSizeEx', 'int (*)(void *, int64_t *)')
    local close_handle = resolve(K, 'CloseHandle', 'int (*)(void *)')
    local query_memory = resolve('ntdll.dll', 'NtQueryVirtualMemory',
        'int32_t (*)(void *, const void *, int32_t, void *, size_t, size_t *)')
    local U = 'user32.dll'
    local key_state = resolve(U, 'GetAsyncKeyState', 'int16_t (*)(int32_t)')
    local foreground_window = resolve(U, 'GetForegroundWindow', 'void *(*)(void)')
    local window_process = resolve(U, 'GetWindowThreadProcessId', 'uint32_t (*)(void *, uint32_t *)')

    local process = get_process()
    local got = ffi.new('size_t[1]')

    local ticks, frequency = ffi.new('int64_t[1]'), ffi.new('int64_t[1]')
    perf_frequency(frequency)
    local per_second = tonumber(frequency[0])
    if not per_second or per_second <= 0 then error('no performance counter') end
    function a.now()
        perf_counter(ticks)
        return tonumber(ticks[0]) / per_second
    end

    -- The allocation holding `address`: base, size, true. For free memory: base, size, false.
    -- NtQueryVirtualMemory's region information costs the same for any allocation size;
    -- VirtualQuery is only used for free memory (in-game it took 9.9 ms on one huge region).
    local info = ffi.new('uint64_t[6]')
    local info32 = ffi.cast('uint32_t *', info)
    local returned = ffi.new('size_t[1]')
    function a.allocation(address)
        local pointer = ffi.cast(cvoid, address)
        if query_memory(process, pointer, 3, info, 48, returned) == 0
            or query_memory(process, pointer, 3, info, 32, returned) == 0 then
            local base, size = tonumber(info[0]), tonumber(info[2])
            if base and size and size > 0 and base <= address then return base, size, true end
        end
        if tonumber(virtual_query(pointer, info, 48)) ~= 48 then return nil end
        local base, size = tonumber(info[0]), tonumber(info[3])
        if not base or not size or size <= 0 then return nil end
        -- state at +32: MEM_FREE 0x10000. Anything else here means region information is not
        -- available on this system; treat the region as one allocation.
        return base, size, info32[8] ~= 0x10000
    end

    -- One page: present in memory?, its protection, shared (mapped) or private.
    local page = ffi.new('uint64_t[2]')
    function a.page(address)
        page[0], page[1] = address - address % 4096, 0
        if working_set(process, page, 16) == 0 then return false end
        local attributes = tonumber(page[1] % 65536)
        if attributes % 2 ~= 1 then return false end
        return true, math.floor(attributes / 16) % 2048, attributes >= 32768
    end
    function a.readable_private(address)
        local present, protection, shared = a.page(address)
        return present and not shared and (protection == PAGE_READWRITE or protection == PAGE_READONLY)
    end

    a.buffer_size = FILE_CHUNK + 16
    a.buffer = ffi.new('uint8_t[?]', a.buffer_size)
    a.words = ffi.cast('uint32_t *', a.buffer)
    function a.read(address, size)
        if size <= 0 or size > a.buffer_size then return false end
        if read_memory(process, ffi.cast(cvoid, address), a.buffer, size, got) == 0 then return false end
        return tonumber(got[0]) == size
    end

    local cell = ffi.new('uint32_t[2]')
    function a.u32(address)
        if read_memory(process, ffi.cast(cvoid, address), cell, 4, got) == 0 then return nil end
        if tonumber(got[0]) ~= 4 then return nil end
        return tonumber(cell[0])
    end
    function a.u64(address)
        if read_memory(process, ffi.cast(cvoid, address), cell, 8, got) == 0 then return nil end
        if tonumber(got[0]) ~= 8 then return nil end
        return tonumber(cell[0]) + tonumber(cell[1]) * 4294967296
    end

    -- The only function in this file that changes game memory: 4 bytes, through the OS.
    local out = ffi.new('uint32_t[1]')
    function a.write_u32(address, bits)
        out[0] = bits
        if write_memory(process, ffi.cast(void, address), out, 4, got) == 0 then return false end
        return tonumber(got[0]) == 4
    end

    -- Changes the protection of the one page holding `address`. -> true when Windows accepted it.
    local old_protection = ffi.new('uint32_t[1]')
    function a.protect(address, protection)
        return virtual_protect(ffi.cast(void, address - address % 4096), 4096, protection, old_protection) ~= 0
    end

    -- f32 -> bit pattern, by copying the bytes of a float (no pointer aliasing).
    local float_cell, bits_cell = ffi.new('float[1]'), ffi.new('uint32_t[1]')
    function a.f32_bits(value)
        float_cell[0] = value
        ffi.copy(bits_cell, float_cell, 4)
        return tonumber(bits_cell[0])
    end

    function a.mkdir(path)
        return create_directory(path, nil) ~= 0 or get_last_error() == 183
    end

    function a.module(name)
        local handle = module_handle(name)
        if handle == nil then return nil end
        local path_buffer = ffi.new('char[1024]')
        local length = module_file_name(handle, path_buffer, 1024)
        return tonumber(ffi.cast('uintptr_t', handle)), length > 0 and ffi.string(path_buffer, length) or nil
    end
    function a.open(path)
        local handle = create_file(path, 0x80000000, 7, nil, 3, 0x08000000, nil)
        if handle == nil or tonumber(ffi.cast('intptr_t', handle)) == -1 then return nil end
        local size = ffi.new('int64_t[1]')
        if file_size(handle, size) == 0 then close_handle(handle); return nil end
        return handle, tonumber(size[0])
    end
    local file_got = ffi.new('uint32_t[1]')
    function a.read_file(handle)
        if read_file(handle, a.buffer, HASH_CHUNK, file_got, nil) == 0 then return nil end
        return tonumber(file_got[0])
    end
    function a.close(handle) close_handle(handle) end

    local B = 'bcrypt.dll'
    local open_algorithm = resolve(B, 'BCryptOpenAlgorithmProvider',
        'int32_t (*)(void **, const uint16_t *, const uint16_t *, uint32_t)')
    local close_algorithm = resolve(B, 'BCryptCloseAlgorithmProvider', 'int32_t (*)(void *, uint32_t)')
    local create_hash = resolve(B, 'BCryptCreateHash',
        'int32_t (*)(void *, void **, uint8_t *, uint32_t, uint8_t *, uint32_t, uint32_t)')
    local hash_data = resolve(B, 'BCryptHashData', 'int32_t (*)(void *, uint8_t *, uint32_t, uint32_t)')
    local finish_hash = resolve(B, 'BCryptFinishHash', 'int32_t (*)(void *, uint8_t *, uint32_t, uint32_t)')
    local destroy_hash = resolve(B, 'BCryptDestroyHash', 'int32_t (*)(void *)')
    local sha256_name = ffi.new('uint16_t[7]', { 83, 72, 65, 50, 53, 54, 0 })   -- L"SHA256"
    function a.sha256_begin()
        local algorithm, hash = ffi.new('void *[1]'), ffi.new('void *[1]')
        if open_algorithm(algorithm, sha256_name, nil, 0) ~= 0 then return nil end
        if create_hash(algorithm[0], hash, nil, 0, nil, 0, 0) ~= 0 then
            close_algorithm(algorithm[0], 0)
            return nil
        end
        return { algorithm = algorithm[0], hash = hash[0] }
    end
    function a.sha256_update(context, size) return hash_data(context.hash, a.buffer, size, 0) == 0 end
    function a.sha256_finish(context)
        local digest = ffi.new('uint8_t[32]')
        local ok = finish_hash(context.hash, digest, 32, 0) == 0
        destroy_hash(context.hash)
        close_algorithm(context.algorithm, 0)
        if not ok then return nil end
        local parts = {}
        for i = 0, 31 do parts[i + 1] = string.format('%02X', digest[i]) end
        return table.concat(parts)
    end

    -- keyboard: is the key down right now, and is the game the window in front?
    local own_process, window_owner = get_process_id(), ffi.new('uint32_t[1]')
    function a.key_down(vk) return key_state(vk) < 0 end
    function a.game_in_front()
        local window = foreground_window()
        if window == nil then return false end
        window_owner[0] = 0
        window_process(window, window_owner)
        return window_owner[0] == own_process
    end

    return a
end

-- ---------------------------------------------------------------- files
local out_dir = nil
local function ensure_out_dir()
    if out_dir then return out_dir end
    local base = os.getenv('LOCALAPPDATA')
    if not base or base == '' then return nil end
    local dir = base .. '\\' .. MOD.dir
    if A then pcall(A.mkdir, dir) end
    out_dir = dir
    return dir
end

-- Writes into our own folder; when that is impossible, into the loader's log folder.
local function write_file(name, text)
    local ok = pcall(function()
        local base = os.getenv('LOCALAPPDATA')
        local dir = ensure_out_dir()
        local handle = dir and io.open(dir .. '\\' .. name, 'wb')
        if not handle and base then
            handle = io.open(base .. '\\CowboyBingus\\Helldivers2\\Logs\\' .. MOD.dir .. '-' .. name, 'wb')
        end
        if not handle then return end
        handle:write(text)
        handle:close()
    end)
    return ok
end

local function read_file(name)
    local dir = ensure_out_dir()
    if not dir then return nil end
    local handle = io.open(dir .. '\\' .. name, 'rb')
    if not handle then return nil end
    local text = handle:read('*a')
    handle:close()
    return text
end

local function flush_log()
    log_dirty = false
    write_file(MOD.log, MOD.title .. ' v' .. MOD.version .. '\r\n'
        .. 'phase: ' .. state.phase .. '   errors: ' .. state.errors .. '\r\n\r\n'
        .. table.concat(log_lines, '\r\n') .. '\r\n')
end

-- ---------------------------------------------------------------- cooperative scheduling
local deadline = 0
local function pause()
    if A.now() >= deadline then coroutine.yield() end
end

-- ---------------------------------------------------------------- generated data
local BUILDS = {}                                    -- { label, exe, dll }
local SPECS, SPEC_BY_TYPE, SPEC_ORDER = {}, {}, {}   -- tables
local ITEMS, ITEM_BY_NAME = {}, {}                   -- index -> item; 'category:name' -> item
local FIELDS = {}                                    -- field key -> field (shared between items)
local RANGES, ALIASES = {}, {}
local field_count = 0

local function field_key(table_name, key, offset) return table_name .. '|' .. key .. '|' .. offset end

local function parse_data()
    local count = 0
    for line in DATA:gmatch('[^\n]+') do
        local kind = line:sub(1, 1)
        local f = {}
        for part in (line .. '|'):gmatch('([^|]*)|') do f[#f + 1] = part end
        if kind == 'V' then
            BUILDS[#BUILDS + 1] = { label = f[2], exe = f[3], dll = f[4] }
        elseif kind == 'T' then
            local spec = { name = f[2], type = tonumber(f[3], 16), shape = f[4],
                           stride = tonumber(f[5]), id_at = tonumber(f[6]), blocks = {} }
            SPECS[spec.name], SPEC_BY_TYPE[spec.type] = spec, spec
            SPEC_ORDER[#SPEC_ORDER + 1] = spec.name
        elseif kind == 'I' then
            local item = { index = tonumber(f[2]), category = f[3], name = f[4], entity = f[5],
                           stats = {}, stat_order = {} }
            ITEMS[item.index] = item
            ITEM_BY_NAME[item.category .. ':' .. item.name:lower()] = item
        elseif kind == 'F' then
            local item = ITEMS[tonumber(f[2])]
            local key = field_key(f[4], f[5], tonumber(f[6]))
            local field = FIELDS[key]
            if not field then
                field = { key = key, table = f[4], record = f[5], offset = tonumber(f[6]), storage = f[7],
                          stock = tonumber(f[8]), users = {} }
                FIELDS[key] = field
                field_count = field_count + 1
            end
            field.users[#field.users + 1] = item.name .. '.' .. f[3]
            if not item.stats[f[3]] then item.stat_order[#item.stat_order + 1] = f[3] end
            item.stats[f[3]] = { field = field, attachment = f[9] == 'A' }
        elseif kind == 'R' then
            RANGES[f[2]] = { min = tonumber(f[3]), max = tonumber(f[4]), integer = f[5] == '1' }
        elseif kind == 'A' then
            local targets = {}
            for name in f[4]:gmatch('[^,]+') do targets[#targets + 1] = name end
            ALIASES[f[2]] = { mode = f[3], targets = targets }
        end
        count = count + 1
        if count % 50 == 0 then pause() end
    end
    log('data: ' .. #BUILDS .. ' builds, ' .. #SPEC_ORDER .. ' tables, ' .. (#ITEMS + 1) .. ' items, '
        .. field_count .. ' fields')
end

-- ---------------------------------------------------------------- build gate
local build = { state = 'unchecked', modules = {} }

local function hash_module(name)
    local info = { name = name or 'helldivers2.exe' }
    local base, path = A.module(name)
    if not base or not path then info.note = 'not loaded'; return info end
    info.path = path
    local handle, size = A.open(path)
    if not handle then info.note = 'file could not be opened'; return info end
    info.file_size = size
    local context = A.sha256_begin()
    if not context then
        info.note = 'SHA-256 unavailable'
    else
        local total, ok = 0, true
        while true do
            local n = A.read_file(handle)
            if n == nil then ok = false break end
            if n == 0 then break end
            if not A.sha256_update(context, n) then ok = false break end
            total = total + n
            pause()
        end
        local digest = A.sha256_finish(context)
        if ok and digest and total == size then info.sha256 = digest
        else info.note = 'hashing failed after ' .. total .. ' bytes' end
    end
    A.close(handle)
    return info
end

-- Sets build.state to 'verified' only when BOTH files hash to the same known build.
local function check_build()
    local exe, dll = hash_module(nil), hash_module('game.dll')
    build.modules = { exe, dll }
    build.state, build.label = 'unknown', nil
    for _, known in ipairs(BUILDS) do
        if exe.sha256 and dll.sha256 and exe.sha256 == known.exe and dll.sha256 == known.dll then
            build.state, build.label = 'verified', known.label
        end
    end
    log('build: ' .. build.state .. (build.label and (' (' .. build.label .. ')') or '')
        .. ' exe=' .. tostring(exe.sha256 or exe.note) .. ' dll=' .. tostring(dll.sha256 or dll.note))
end

-- ---------------------------------------------------------------- finding tables
local search = { passes = 0, allocations = 0, seconds = 0, slowest_query = 0, slowest_at = 0 }

local function valid_block(block)
    return A.u32(block.address) == LDLD and A.u32(block.address + 4) == 1
        and A.u32(block.address + 8) == block.type and A.u32(block.address + 12) == block.size
end

-- Follows a chain of back-to-back blocks from `address`; keeps the blocks of wanted tables.
local function walk(address, origin, found)
    local steps = 0
    while steps < 200000 do
        if A.u32(address) ~= LDLD or A.u32(address + 4) ~= 1 then return end
        local kind, size = A.u32(address + 8), A.u32(address + 12)
        if not kind or kind == 0 or not size or size == 0 or size > MAX_BLOCK then return end
        local spec = SPEC_BY_TYPE[kind]
        if spec and not found[address] then
            found[address] = { address = address, type = kind, size = size, spec = spec,
                               origin = steps == 0 and origin or 'chain' }
        end
        steps = steps + 1
        local after, next_address = address + 24 + size, nil
        for skip = 0, 16, 4 do
            if A.u32(after + skip) == LDLD and A.u32(after + skip + 4) == 1 then
                next_address = after + skip
                break
            end
        end
        if not next_address then return end
        address = next_address
        pause()
    end
end

-- One pass over the allocations of the process: is there a table at the start of each?
-- (In-game recon: every table we use sits there or in the chain behind one.)
local function find_tables()
    local started, found = A.now(), {}
    search.allocations = 0
    local cursor = ADDRESS_START
    while cursor < ADDRESS_END do
        local t0 = A.now()
        local base, size, allocated = A.allocation(cursor)
        local cost = A.now() - t0
        if cost > search.slowest_query then search.slowest_query, search.slowest_at = cost, cursor end
        if not base then break end
        if allocated then
            search.allocations = search.allocations + 1
            if A.readable_private(base) then
                if A.u32(base) == LDLD and A.u32(base + 4) == 1 then
                    walk(base, 'allocation+0', found)
                elseif A.u32(base + 4) == LDLD and A.u32(base + 8) == 1 then
                    walk(base + 4, 'allocation+4', found)
                end
            end
        end
        local next_cursor = base + size
        if next_cursor <= cursor then next_cursor = cursor + 4096 end
        cursor = next_cursor
        pause()
    end
    -- merge: keep parsed blocks that are still there, add new ones, drop the rest
    for _, name in ipairs(SPEC_ORDER) do
        local spec, kept = SPECS[name], {}
        for _, block in ipairs(spec.blocks) do
            if found[block.address] and found[block.address].size == block.size then
                kept[#kept + 1] = block
                found[block.address] = nil
            end
        end
        spec.blocks = kept
    end
    for _, block in pairs(found) do
        block.spec.blocks[#block.spec.blocks + 1] = block
    end
    for _, name in ipairs(SPEC_ORDER) do
        table.sort(SPECS[name].blocks, function(x, y) return x.address < y.address end)
    end
    search.passes = search.passes + 1
    search.seconds = A.now() - started
    state.passes = search.passes
end

-- Keyed table: buckets (u64 entity, u32 record index, u32 0), twice as many as entities, then
-- fixed-size records. The bucket count is derived from the content, never assumed.
local function parse_keyed(block)
    local payload, size, stride = block.address + 24, block.size, block.spec.stride
    local limit = math.floor(size / (16 + stride / 2)) + 4
    local count, live, top, fits = 0, 0, -1, {}
    local offset, stop = 0, false
    while not stop and offset + 16 <= size and count <= limit do
        local want = math.min(8192, size - offset)
        want = want - want % 16
        if want < 16 or not A.read(payload + offset, want) then break end
        local w = A.words
        for k = 0, want / 16 - 1 do
            local lo, hi, index, pad = w[k * 4], w[k * 4 + 1], w[k * 4 + 2], w[k * 4 + 3]
            if pad ~= 0 or index > 1000000 or count > limit then stop = true break end
            count = count + 1
            if lo ~= 0 or hi ~= 0 then
                live = live + 1
                if index > top then top = index end
            end
            local rest = size - count * 16
            if count == 2 * live and rest > 0 and rest % stride < 8 then
                local records = (rest - rest % stride) / stride
                if records > top and records <= live + 2 then
                    fits[#fits + 1] = { buckets = count, records = records }
                end
            end
        end
        offset = offset + want
        pause()
    end
    if #fits ~= 1 then return nil, #fits .. ' bucket layouts fit (need exactly 1)' end
    local fit, index = fits[1], {}
    offset = 0
    while offset < fit.buckets * 16 do
        local want = math.min(8192, fit.buckets * 16 - offset)
        if not A.read(payload + offset, want) then return nil, 'bucket array unreadable' end
        local w = A.words
        for k = 0, want / 16 - 1 do
            local lo, hi = w[k * 4], w[k * 4 + 1]
            if lo ~= 0 or hi ~= 0 then
                local key = string.format('%08X%08X', hi, lo)
                if index[key] == nil then
                    local record = w[k * 4 + 2]
                    if record >= fit.records then return nil, 'record index out of range' end
                    index[key] = record
                end
            end
        end
        offset = offset + want
        pause()
    end
    block.records_at, block.index, block.count = payload + fit.buckets * 16, index, fit.records
    block.limit = payload + size
    return true
end

-- Row table: DLArray (u64 absolute pointer in memory, u64 count), then rows carrying a u32 id.
local function parse_rows(block)
    local payload, size, stride = block.address + 24, block.size, block.spec.stride
    local pointer, count = A.u64(payload), A.u64(payload + 8)
    if not pointer or not count then return nil, 'array head unreadable' end
    local rows_at
    if pointer < size then rows_at = payload + pointer
    elseif pointer >= payload and pointer < payload + size then rows_at = pointer
    else return nil, 'rows are outside the block' end
    if count == 0 or (rows_at - payload) + count * stride > size then
        return nil, 'rows do not fit (count ' .. count .. ')'
    end
    local index = {}
    local per_read = math.max(1, math.floor(FILE_CHUNK / stride))
    local row = 0
    while row < count do
        local n = math.min(per_read, count - row)
        if not A.read(rows_at + row * stride, n * stride) then return nil, 'rows unreadable' end
        local bytes = A.buffer
        for k = 0, n - 1 do
            local at = k * stride + block.spec.id_at
            local id = bytes[at] + bytes[at + 1] * 256 + bytes[at + 2] * 65536 + bytes[at + 3] * 16777216
            if index[id] == nil then index[id] = row + k end
        end
        row = row + n
        pause()
    end
    block.records_at, block.index, block.count = rows_at, index, count
    block.limit = payload + size
    return true
end

local function parse_block(block)
    if block.index or block.problem then return block.index ~= nil end
    state.step = 'reading table ' .. block.spec.name
    local ok, why
    if block.spec.shape == 'K' then ok, why = parse_keyed(block) else ok, why = parse_rows(block) end
    if not ok then
        block.problem = why
        log(block.spec.name .. ' at ' .. hex(block.address) .. ' cannot be parsed: ' .. tostring(why))
    end
    return ok == true
end

-- Address of `field` in `block`, or nil when the record is not in this table.
local function field_address(block, field)
    local key = field.record
    if block.spec.shape == 'R' then key = tonumber(key) end
    local record = block.index[key]
    if record == nil then return nil end
    local address = block.records_at + record * block.spec.stride + field.offset
    if address < block.address + 24 or address + 4 > block.limit then return nil end
    return address
end

local function read_field(address, storage)
    local bits = A.u32(address)
    if bits == nil then return nil end
    if storage == 'f32' then return bits_to_f32(bits) end
    if storage == 'i32' and bits >= 2147483648 then return bits - 4294967296 end
    return bits
end

-- value -> bit pattern, or nil when it cannot be represented exactly as intended
local function encode(value, storage)
    if storage == 'f32' then
        local bits = A.f32_bits(value)
        if not close_enough(bits_to_f32(bits), value) then return nil end   -- encoder vs decoder
        return bits
    end
    if value ~= math.floor(value) then return nil end
    if storage == 'i32' then
        if value < -2147483648 or value > 2147483647 then return nil end
        if value < 0 then return value + 4294967296 end
        return value
    end
    if value < 0 or value > 4294967295 then return nil end
    return value
end

-- ---------------------------------------------------------------- config
local config = { text = nil, enabled = true, reload_vk = 0x79, reload_key = 'F10', auto_reload = 0,
                 rescan = DEFAULT_RESCAN_SECONDS, requests = {}, problems = {} }
local overrides = {}     -- 'category:item:stat' -> expression, set through the API (a future UI)
-- field key -> { field, value, copies = { [block address] = { address, original, block } },
--                state, note }: what the engine has touched in memory
local applied = {}
local desired = {}       -- field key -> { field, value, sources = { request, ... } }

local TEMPLATE = table.concat({
    '# HD2 Stat Tuner config. Lines starting with # are comments.',
    '# After editing, press the reload key in game (default F10). Remove a line to get the',
    "# game's own value back. Items, stats and allowed ranges: see catalog.txt in this folder.",
    '',
    '[settings]',
    'enabled = true',
    'reload_key = F10',
    'auto_reload_seconds = 0',
    '',
    '# Example (remove the # to use it):',
    '# [weapon: assault_rifle]',
    '# damage = 120',
    '# rpm = 150%',
    '# recoil = -5',
    '',
}, '\r\n')

local function parse_bool(text)
    text = text:lower()
    if text == 'true' or text == 'yes' or text == 'on' or text == '1' then return true end
    if text == 'false' or text == 'no' or text == 'off' or text == '0' then return false end
    return nil
end

-- 'N', 'N%', '+N', '-N' applied to the game's value -> number, or nil + reason
local function evaluate(expression, stock)
    local text = expression:gsub('%s+', ''):gsub(',', '.')
    local percent = text:match('^([%d%.]+)%%$')
    if percent then
        local n = tonumber(percent)
        if not n then return nil, 'not a number' end
        return stock * n / 100
    end
    local sign, amount = text:match('^([%+%-])([%d%.]+)$')
    if sign then
        local n = tonumber(amount)
        if not n then return nil, 'not a number' end
        if sign == '+' then return stock + n end
        return stock - n
    end
    local n = text:match('^[%d%.]+$') and tonumber(text)
    if not n then return nil, 'not a number (use 120, 150%, +15 or -5)' end
    return n
end

-- Turns one request (category, item, stat, expression) into field targets, or rejects it.
local function resolve_request(request)
    local item = ITEM_BY_NAME[request.category .. ':' .. request.item:lower()]
    if not item then
        request.status, request.reason = 'rejected', 'unknown ' .. request.category .. ' (see catalog.txt)'
        return
    end
    local stats, nonzero = { request.stat }, false
    local alias = ALIASES[request.stat]
    if alias then stats, nonzero = alias.targets, alias.mode == 'nonzero' end
    request.targets = {}
    for _, stat in ipairs(stats) do
        local entry, range = item.stats[stat], RANGES[stat]
        if entry and range and not (nonzero and entry.field.stock == 0) then
            if entry.attachment then
                request.status = 'rejected'
                request.reason = stat .. " is set by this weapon's default attachment; not editable in this version"
                return
            end
            local value, why = evaluate(request.expression, entry.field.stock)
            if not value then request.status, request.reason = 'rejected', why return end
            if range.integer or entry.field.storage ~= 'f32' then value = math.floor(value + 0.5) end
            if value ~= value or value < range.min or value > range.max then
                request.status = 'rejected'
                request.reason = string.format('%s = %s is outside the allowed range %s .. %s', stat,
                    show(value, 'f32'), show(range.min, 'f32'), show(range.max, 'f32'))
                return
            end
            if encode(value, entry.field.storage) == nil then
                request.status, request.reason = 'rejected', stat .. ' = ' .. tostring(value) .. ' cannot be stored'
                return
            end
            request.targets[#request.targets + 1] = { stat = stat, field = entry.field, value = value }
        elseif not alias then
            request.status = 'rejected'
            request.reason = 'this ' .. request.category .. ' has no stat "' .. stat .. '" (see catalog.txt)'
            return
        end
    end
    if #request.targets == 0 then
        request.status, request.reason = 'rejected', 'nothing to set: no "' .. request.stat .. '" value on this item'
        return
    end
    request.status = 'accepted'
end

-- Parses the config text and the API overrides into `desired`.
local function build_desired(text)
    config.requests, config.problems = {}, {}
    config.enabled, config.reload_key, config.reload_vk = true, 'F10', 0x79
    config.auto_reload, config.rescan = 0, DEFAULT_RESCAN_SECONDS
    local section, line_number = nil, 0
    local by_stat = {}   -- 'category:item:stat' -> request (a later line replaces an earlier one)
    for raw in ((text or '') .. '\n'):gmatch('([^\n]*)\n') do
        line_number = line_number + 1
        local line = trim((raw:gsub('#.*$', ''):gsub('\r', '')))
        if line ~= '' then
            local header = line:match('^%[(.-)%]$')
            local key, value = line:match('^([^=]+)=(.*)$')
            if header then
                local category, item = header:match('^%s*([%w_]+)%s*:%s*(.-)%s*$')
                if trim(header):lower() == 'settings' then
                    section = { settings = true }
                elseif category and item ~= '' then
                    section = { category = category:lower(), item = item }
                else
                    section = nil
                    config.problems[#config.problems + 1] = 'line ' .. line_number .. ': cannot read section "' .. line .. '"'
                end
            elseif key and section then
                key, value = trim(key):lower(), trim(value)
                if section.settings then
                    if key == 'enabled' and parse_bool(value) ~= nil then
                        config.enabled = parse_bool(value)
                    elseif key == 'reload_key' and value:upper():match('^F%d%d?$')
                        and tonumber(value:sub(2)) >= 1 and tonumber(value:sub(2)) <= 12 then
                        config.reload_key = value:upper()
                        config.reload_vk = 0x6F + tonumber(value:sub(2))
                    elseif key == 'auto_reload_seconds' and tonumber(value) and tonumber(value) >= 0 then
                        config.auto_reload = tonumber(value)
                    elseif key == 'rescan_seconds' and tonumber(value) and tonumber(value) >= 0 then
                        config.rescan = tonumber(value)
                    else
                        config.problems[#config.problems + 1] = 'line ' .. line_number .. ': unknown setting "' .. line .. '"'
                    end
                else
                    local request = { line = line_number, category = section.category, item = section.item,
                                      stat = key, expression = value, text = line }
                    by_stat[section.category .. ':' .. section.item:lower() .. ':' .. key] = request
                    config.requests[#config.requests + 1] = request
                end
            else
                config.problems[#config.problems + 1] = 'line ' .. line_number .. ': cannot read "' .. line .. '"'
            end
        end
    end
    for key, expression in pairs(overrides) do
        local category, item, stat = key:match('^([^:]+):([^:]+):(.+)$')
        local previous = by_stat[key]
        if previous then previous.status, previous.reason = 'replaced', 'replaced through the API' end
        local request = { line = 0, category = category, item = item, stat = stat, expression = expression,
                          text = stat .. ' = ' .. expression .. ' (API)' }
        by_stat[key] = request
        config.requests[#config.requests + 1] = request
    end
    -- a later line for the same item and stat replaces the earlier one
    for _, request in ipairs(config.requests) do
        local key = request.category .. ':' .. request.item:lower() .. ':' .. request.stat
        if not request.status and by_stat[key] ~= request then
            request.status, request.reason = 'replaced', 'a later line sets the same stat'
        end
    end
    desired = {}
    if not config.enabled then
        for _, request in ipairs(config.requests) do
            if not request.status then request.status, request.reason = 'off', 'enabled = false' end
        end
        return
    end
    for _, request in ipairs(config.requests) do
        if not request.status then resolve_request(request) end
    end
    -- shared values: different targets for the same field reject every request involved
    local claims = {}
    for _, request in ipairs(config.requests) do
        if request.status == 'accepted' then
            for _, target in ipairs(request.targets) do
                local claim = claims[target.field.key]
                if not claim then
                    claims[target.field.key] = { value = target.value, requests = { request }, field = target.field }
                else
                    claim.requests[#claim.requests + 1] = request
                    if not same_value(target.field.storage, claim.value, target.value) then claim.conflict = true end
                end
            end
        end
    end
    for _, claim in pairs(claims) do
        if claim.conflict then
            local lines = {}
            for _, request in ipairs(claim.requests) do lines[#lines + 1] = request.line end
            table.sort(lines)
            for _, request in ipairs(claim.requests) do
                request.status = 'rejected'
                request.reason = 'lines ' .. table.concat(lines, ', ')
                    .. ' ask for different values of the same shared value (' .. claim.field.table .. ' '
                    .. claim.field.record .. ' +' .. claim.field.offset .. ')'
            end
        end
    end
    for _, request in ipairs(config.requests) do
        if request.status == 'accepted' then
            for _, target in ipairs(request.targets) do
                local entry = desired[target.field.key]
                if not entry then
                    entry = { field = target.field, value = target.value, sources = {} }
                    desired[target.field.key] = entry
                end
                entry.sources[#entry.sources + 1] = request
            end
        end
    end
end

local function load_config()
    local text = read_file(MOD.config)
    if text == nil then
        write_file(MOD.config, TEMPLATE)
        text = TEMPLATE
        log('config.txt did not exist: template written')
    end
    config.text = text
    build_desired(text)
    local accepted = 0
    for _ in pairs(desired) do accepted = accepted + 1 end
    state.reloads = state.reloads + 1
    state.report_pending = true
    log('#' .. state.reloads .. ' config loaded: ' .. #config.requests .. ' lines, ' .. accepted .. ' values to set')
end

-- STATUS.txt only shows the latest state; the log keeps what every reload did.
local function log_results()
    state.report_pending = false
    local tag = '#' .. state.reloads .. ' '
    for _, request in ipairs(config.requests) do
        local head = tag .. '[' .. request.category .. ': ' .. request.item .. '] ' .. request.text
        if request.status ~= 'accepted' then
            log(head .. ' -> ' .. tostring(request.status) .. ': ' .. tostring(request.reason))
        else
            for _, target in ipairs(request.targets) do
                local entry = applied[target.field.key]
                log(head .. ' -> ' .. target.stat .. ' = ' .. show(target.value, target.field.storage) .. ' '
                    .. (entry and entry.state or 'waiting') .. (entry and entry.note and (' (' .. entry.note .. ')') or ''))
            end
        end
    end
end

-- ---------------------------------------------------------------- applying

local function needed_tables()
    local needed = {}
    for _, entry in pairs(desired) do needed[entry.field.table] = true end
    for _, entry in pairs(applied) do needed[entry.field.table] = true end
    return needed
end

local function missing_tables()
    local missing = {}
    for name in pairs(needed_tables()) do
        local usable = false
        for _, block in ipairs(SPECS[name].blocks) do
            if not block.problem then usable = true end
        end
        if not usable then missing[#missing + 1] = name end
    end
    table.sort(missing)
    return missing
end

-- Writes one value into one copy: checks, write, read back. -> true, or false + reason
local function write_checked(address, field, value)
    local bits = encode(value, field.storage)
    if bits == nil then return false, 'value cannot be stored' end
    local present, protection, shared = A.page(address)
    if not present or shared then return false, 'memory page is not present or not private' end
    local unlocked = false
    if protection == PAGE_READONLY then
        -- In game the component tables (fire rate, handling, magazines...) are in read-only pages.
        if address % 4096 > 4092 or not A.protect(address, PAGE_READWRITE) then
            return false, 'the read-only page could not be made writable'
        end
        unlocked = true
        state.unlocks = state.unlocks + 1
    elseif protection ~= PAGE_READWRITE then
        return false, 'memory page is not writable (protection ' .. tostring(protection) .. ')'
    end
    local wrote = A.write_u32(address, bits)
    if unlocked then
        -- back to read-only whatever happened, and make sure it really is
        local restored = A.protect(address, PAGE_READONLY)
        local _, now = A.page(address)
        if not restored or now ~= PAGE_READONLY then
            state.left_open = state.left_open + 1
            state.errors = state.errors + 1
            log('page of ' .. hex(address) .. ' could not be put back to read-only')
        end
    end
    if not wrote then return false, 'the write was refused by Windows' end
    state.writes = state.writes + 1
    local back = read_field(address, field.storage)
    if not same_value(field.storage, back, value) then
        return false, 'read-back mismatch: wrote ' .. show(value, field.storage) .. ', read ' .. show(back, field.storage)
    end
    return true
end

-- Brings one field to `value` in every copy of its table (value nil: back to the original).
local function sync_field(entry, value)
    local field, spec = entry.field, SPECS[entry.field.table]
    state.step = 'applying ' .. field.table
    local range = nil
    for _, user in ipairs(field.users) do range = range or RANGES[user:match('%.(.+)$')] end
    local seen, done, waiting = {}, 0, 0
    for _, block in ipairs(spec.blocks) do
        seen[block.address] = true
        if parse_block(block) then
            local address = field_address(block, field)
            if address then
                local copy = entry.copies[block.address]
                local current = read_field(address, field.storage)
                if current == nil then
                    entry.note = 'value unreadable at ' .. hex(address)
                else
                    if not copy then
                        -- first touch of this copy: remember what the game had
                        copy = { address = address, original = current, block = block }
                        if not same_value(field.storage, current, field.stock) then
                            copy.foreign = true   -- not the game's stock value: another mod, or an update
                        end
                        entry.copies[block.address] = copy
                    end
                    local target = value
                    if target == nil then target = copy.original end
                    if same_value(field.storage, current, target) then
                        done = done + 1
                    elseif range and (current < range.min - 0.5 or current > range.max + 0.5)
                        and not same_value(field.storage, current, field.stock) then
                        entry.note = 'current value ' .. show(current, field.storage) .. ' is implausible; not touched'
                    else
                        local ok, why = write_checked(address, field, target)
                        if ok then
                            done = done + 1
                            if copy.written then state.rewrites = state.rewrites + 1 end
                            copy.written = value ~= nil
                            if value == nil then state.restores = state.restores + 1 end
                        else
                            entry.note = why
                            state.errors = state.errors + 1
                            log(field.key .. ' at ' .. hex(address) .. ': ' .. why)
                        end
                    end
                end
            else
                entry.note = 'record not found in the table'
            end
        else
            waiting = waiting + 1
        end
        pause()
    end
    for address in pairs(entry.copies) do
        if not seen[address] then entry.copies[address] = nil end   -- that copy is gone
    end
    entry.done = done
    return done
end

-- Makes memory match `desired`: sets what is asked for, restores what no longer is.
local function sync()
    for key, want in pairs(desired) do
        local entry = applied[key]
        if not entry then
            entry = { field = want.field, copies = {} }
            applied[key] = entry
        end
        entry.value, entry.sources, entry.note = want.value, want.sources, nil
        local done = sync_field(entry, want.value)
        entry.state = done > 0 and not entry.note and 'applied' or (entry.note and 'failed' or 'waiting')
    end
    for key, entry in pairs(applied) do
        if not desired[key] then
            entry.note = nil
            local copies = 0
            for _ in pairs(entry.copies) do copies = copies + 1 end
            sync_field(entry, nil)
            if not entry.note or copies == 0 then applied[key] = nil
            else entry.state = 'restore failed' end
        end
    end
end

-- Cheap check of everything applied: block still there, value still ours. -> 'ok' | 'lost' | 'changed'
local function recheck()
    local result = 'ok'
    for _, entry in pairs(applied) do
        for _, copy in pairs(entry.copies) do
            if not valid_block(copy.block) then
                return 'lost'
            end
            -- only values we actually wrote can be "changed back"; a refused write is not retried
            if entry.value ~= nil and copy.written then
                local current = read_field(copy.address, entry.field.storage)
                if not same_value(entry.field.storage, current, entry.value) then result = 'changed' end
            end
        end
        pause()
    end
    return result
end

-- ---------------------------------------------------------------- reports
local function count_states()
    local counts = { applied = 0, waiting = 0, failed = 0, rejected = 0, lines = 0 }
    for _, request in ipairs(config.requests) do
        if request.status ~= 'replaced' then counts.lines = counts.lines + 1 end
        if request.status == 'rejected' then counts.rejected = counts.rejected + 1 end
    end
    for key in pairs(desired) do
        local entry = applied[key]
        local s = entry and entry.state or 'waiting'
        if s == 'applied' then counts.applied = counts.applied + 1
        elseif s == 'waiting' then counts.waiting = counts.waiting + 1
        else counts.failed = counts.failed + 1 end
    end
    return counts
end

local function build_status()
    local L = {}
    local function add(text) L[#L + 1] = text end
    local counts = count_states()
    local verdict
    if state.phase == 'gave_up' then
        verdict = 'FAILED - ' .. tostring(state.failure)
    elseif build.state == 'unchecked' then
        verdict = 'WAITING - checking the game build (nothing written yet)'
    elseif build.state ~= 'verified' then
        verdict = 'REFUSED - this game build is not one this version was verified on; nothing was written'
    elseif not config.enabled then
        verdict = 'DISABLED - enabled = false in config.txt; all values are the game\'s own'
    elseif counts.applied + counts.waiting + counts.failed + counts.rejected == 0 then
        verdict = 'OK - no changes configured'
    elseif counts.waiting + counts.failed + counts.rejected == 0 then
        verdict = 'OK - ' .. counts.applied .. ' values applied'
    else
        verdict = string.format('PARTIAL - %d values applied, %d waiting for their table, %d failed, %d config lines rejected',
                                counts.applied, counts.waiting, counts.failed, counts.rejected)
    end
    state.verdict = verdict
    add(verdict)
    add(MOD.title .. ' v' .. MOD.version)
    add(string.format('phase=%s frame=%d errors=%d writes=%d restores=%d rewrites=%d reloads=%d', state.phase,
                      state.frame, state.errors, state.writes, state.restores, state.rewrites, state.reloads))
    add(string.format('read-only pages opened for a write=%d, not closed again=%d', state.unlocks, state.left_open))
    local loader = rawget(_G, 'CowboyBingusModLoader')
    add('loader: ' .. (type(loader) == 'table' and ('api=' .. tostring(loader.api) .. ' version=' .. tostring(loader.version))
                       or 'CowboyBingusModLoader global not found'))
    if rawget(_G, 'HD2StatTunerRecon') then add('note: the recon build is also installed; remove it, both write STATUS.txt') end
    add('')
    add('[build] ' .. build.state .. (build.label and (': ' .. build.label) or ''))
    for _, m in ipairs(build.modules) do
        add(string.format('%s: size=%s sha256=%s%s', m.name, tostring(m.file_size), tostring(m.sha256),
                          m.note and ('  note: ' .. m.note) or ''))
    end
    if build.state == 'unknown' then
        add('known builds:')
        for _, known in ipairs(BUILDS) do add('  ' .. known.label .. ' exe=' .. known.exe .. ' dll=' .. known.dll) end
    end
    add('')
    add(string.format('[settings] enabled=%s reload_key=%s auto_reload_seconds=%s rescan_seconds=%s', tostring(config.enabled),
                      config.reload_key, tostring(config.auto_reload), tostring(config.rescan)))
    for _, problem in ipairs(config.problems) do add('config problem: ' .. problem) end
    add('')
    add('[tables] needed by the config: name copies | address size origin')
    local needed, names = needed_tables(), {}
    for name in pairs(needed) do names[#names + 1] = name end
    table.sort(names)
    for _, name in ipairs(names) do
        local spec = SPECS[name]
        add(name .. ' copies=' .. #spec.blocks)
        for _, block in ipairs(spec.blocks) do
            add(string.format('  %s size=%d origin=%s%s', hex(block.address), block.size, tostring(block.origin),
                              block.problem and (' PROBLEM: ' .. block.problem) or ''))
        end
    end
    if #names == 0 then add('none') end
    add(string.format('search: passes=%d allocations=%d last_pass_seconds=%.2f slowest_query_ms=%.2f at %s',
                      search.passes, search.allocations, search.seconds, search.slowest_query * 1000,
                      hex(search.slowest_at)))
    add('')
    add('[config lines]')
    for _, request in ipairs(config.requests) do
        local head = string.format('line %d [%s: %s] %s', request.line, request.category, request.item, request.text)
        if request.status ~= 'accepted' then
            add(head .. ' -> ' .. tostring(request.status):upper() .. ': ' .. tostring(request.reason))
        else
            add(head)
            for _, target in ipairs(request.targets) do
                local entry, field = applied[target.field.key], target.field
                local copies, originals, foreign = 0, {}, false
                if entry then
                    for _, copy in pairs(entry.copies) do
                        copies = copies + 1
                        originals[show(copy.original, field.storage)] = true
                        foreign = foreign or copy.foreign
                    end
                end
                local was = {}
                for text in pairs(originals) do was[#was + 1] = text end
                table.sort(was)
                local others = {}
                for _, user in ipairs(field.users) do
                    if user ~= request.item:lower() .. '.' .. target.stat and #others < 12 then others[#others + 1] = user end
                end
                add(string.format('  %s: %s -> %s  %s  copies=%d%s%s%s', target.stat,
                    #was > 0 and table.concat(was, '/') or show(field.stock, field.storage),
                    show(target.value, field.storage),
                    (entry and entry.state or 'waiting'):upper(), copies,
                    entry and entry.note and ('  (' .. entry.note .. ')') or '',
                    foreign and '  (the value was not the game\'s stock value before we changed it)' or '',
                    #others > 0 and ('  also affects: ' .. table.concat(others, ', ')
                                     .. (#field.users - 1 > #others and ', ...' or '')) or ''))
            end
        end
    end
    if #config.requests == 0 then add('none') end
    local leftovers = {}
    for key, entry in pairs(applied) do
        if not desired[key] then leftovers[#leftovers + 1] = key .. ': ' .. tostring(entry.state) .. ' (' .. tostring(entry.note) .. ')' end
    end
    if #leftovers > 0 then
        add('')
        add('[not restored]')
        table.sort(leftovers)
        for _, line in ipairs(leftovers) do add(line) end
    end
    add('')
    add(string.format('[cost] worst_frame_ms=%.2f (during: %s) busy_frames=%d busy_seconds=%.2f',
                      state.worst_frame * 1000, tostring(state.worst_step), state.busy_frames, state.busy_seconds))
    return table.concat(L, '\r\n') .. '\r\n'
end

local last_status = nil
local function write_status(force)
    local ok, text = pcall(build_status)
    if not ok then
        log('status: ' .. tostring(text))
        text = 'FAILED - could not build the status report: ' .. tostring(text) .. '\r\n'
            .. MOD.title .. ' v' .. MOD.version .. '\r\n'
    end
    -- the cost line changes all the time: only rewrite the file when something else did
    local stable = text:gsub('%[cost%][^\r\n]*', ''):gsub('frame=%d+', '')
    if force or stable ~= last_status then
        last_status = stable
        write_file(MOD.status, text)
    end
    if log_dirty then flush_log() end
end

-- Written a few items at a time, so that no frame pays for the whole file.
local function write_catalog()
    local dir = ensure_out_dir()
    local handle = dir and io.open(dir .. '\\' .. MOD.catalog, 'wb')
    if not handle then return end
    handle:write(table.concat({ MOD.title .. ' v' .. MOD.version .. ' catalog',
        'category | item | stat | game value | allowed range | notes',
        'Use these names in config.txt:  [category: item]  then  stat = value', '', '' }, '\r\n'))
    for index = 0, #ITEMS do
        local item = ITEMS[index]
        if item then
            local L = { '[' .. item.category .. ': ' .. item.name .. ']' }
            for _, stat in ipairs(item.stat_order) do
                local entry, range = item.stats[stat], RANGES[stat]
                local notes = {}
                if entry.attachment then notes[#notes + 1] = 'set by the default attachment: not editable yet' end
                if #entry.field.users > 1 then notes[#notes + 1] = 'shared with ' .. (#entry.field.users - 1) .. ' other' end
                L[#L + 1] = string.format('  %s = %s   (%s .. %s%s)%s', stat, show(entry.field.stock, entry.field.storage),
                    show(range.min, 'f32'), show(range.max, 'f32'), range.integer and ', whole numbers' or '',
                    #notes > 0 and ('   # ' .. table.concat(notes, '; ')) or '')
            end
            L[#L + 1] = ''
            handle:write(table.concat(L, '\r\n') .. '\r\n')
        end
        if index % 2 == 0 then pause() end
    end
    handle:write('Shortcuts: ap, blast_ap (every angle that is not 0), recoil, recoil_h, recoil_v, spread, magazine, '
        .. 'spare_magazines, carried\r\n')
    handle:close()
end

-- ---------------------------------------------------------------- the worker
local wake = { at = 0, reload = false, config_check_at = 0 }

local function sleep(seconds)
    wake.at = A.now() + seconds
    coroutine.yield()
end

local function worker_main()
    state.step = 'reading the built-in data'
    parse_data()
    state.phase, state.step = 'checking the build', 'hashing the game files'
    write_status(true)
    check_build()
    state.step = 'reading config.txt'
    load_config()
    state.step = 'writing catalog.txt'
    write_catalog()
    local backoff, next_rescan = 1, 0
    while true do
        if wake.reload then
            wake.reload = false
            state.step = 'reading config.txt'
            load_config()
            backoff = 1
        end
        if build.state ~= 'verified' then
            state.phase = 'refused'
            write_status()
            sleep(3600)
        else
            local missing = missing_tables()
            local have_work = next(desired) ~= nil or next(applied) ~= nil
            local rescan_due = have_work and config.rescan > 0 and A.now() >= next_rescan
            if have_work and (#missing > 0 or state.lost or rescan_due) then
                state.phase, state.step = 'searching', 'searching for tables'
                find_tables()
                state.lost = false
                next_rescan = A.now() + (config.rescan > 0 and config.rescan or 0)
            end
            if have_work then
                state.phase, state.step = 'applying', 'applying values'
                sync()
                state.step = 'writing STATUS.txt'
            end
            if state.report_pending then
                local ok_report, why_report = pcall(log_results)
                if not ok_report then log('report: ' .. tostring(why_report)) end
            end
            missing = missing_tables()
            if not have_work then
                state.phase = 'idle'
                write_status()
                sleep(3600)
            elseif #missing > 0 then
                state.phase = 'waiting for tables'
                write_status()
                sleep(SEARCH_BACKOFF[math.min(backoff, #SEARCH_BACKOFF)])
                backoff = backoff + 1
            else
                backoff = 1
                state.phase = 'applied'
                write_status()
                -- asleep: only cheap read-backs until something needs attention
                while not wake.reload do
                    sleep(RECHECK_SECONDS)
                    if wake.reload then break end
                    state.step = 'rechecking applied values'
                    local result = recheck()
                    if result == 'lost' then
                        state.lost = true
                        log('a patched table is gone (map load?): searching again')
                        break
                    elseif result == 'changed' then
                        log('a patched value was changed back: applying again')
                        break
                    elseif config.rescan > 0 and A.now() >= next_rescan then
                        break
                    end
                end
            end
        end
    end
end

-- ---------------------------------------------------------------- per frame
local worker, key_was_down, last_key_reload = nil, false, -1000

local function request_reload()
    wake.reload, wake.at = true, 0
end

local function tick()
    state.frame = state.frame + 1
    if state.frame < START_FRAME then return end
    -- the reload key: one key-state read per frame; the window is only checked on a press
    local down = A.key_down(config.reload_vk)
    if down and not key_was_down and A.game_in_front() then
        local pressed_at = A.now()
        if pressed_at - last_key_reload >= RELOAD_DEBOUNCE then
            last_key_reload = pressed_at
            log('reload key pressed')
            request_reload()
        end
    end
    key_was_down = down
    if state.frame % STEP_EVERY ~= 0 then return end
    local now = A.now()
    if config.auto_reload > 0 and now >= wake.config_check_at and build.state == 'verified' then
        wake.config_check_at = now + config.auto_reload
        local text = read_file(MOD.config)
        if text ~= nil and text ~= config.text then
            log('config.txt changed on disk')
            request_reload()
        end
    end
    if now < wake.at then return end
    if not worker then worker = coroutine.create(worker_main) end
    deadline = now + FRAME_BUDGET
    local ok, why = coroutine.resume(worker)
    local cost = A.now() - now
    state.busy_frames, state.busy_seconds = state.busy_frames + 1, state.busy_seconds + cost
    if cost > state.worst_frame then state.worst_frame, state.worst_step = cost, tostring(state.step) end
    if not ok then
        state.errors = state.errors + 1
        log('worker failed: ' .. tostring(why))
        worker = nil
        if state.errors >= 5 then
            state.phase, state.failure = 'gave_up', 'too many errors, last: ' .. tostring(why)
            state.retired = true
            write_status(true)
        else
            wake.at = A.now() + 5
            write_status(true)
        end
    end
end

-- ---------------------------------------------------------------- API (for a future UI)
-- Read access to everything the engine knows, and a way to change values without the file.
state.api = {
    version = 1,
    categories = function()
        local seen, list = {}, {}
        for index = 0, #ITEMS do
            local item = ITEMS[index]
            if item and not seen[item.category] then seen[item.category] = true; list[#list + 1] = item.category end
        end
        return list
    end,
    items = function(category)
        local list = {}
        for index = 0, #ITEMS do
            local item = ITEMS[index]
            if item and item.category == category then list[#list + 1] = item.name end
        end
        return list
    end,
    -- -> list of { id, game, current, min, max, integer, editable, shared_with }
    stats = function(category, name)
        local item = ITEM_BY_NAME[tostring(category) .. ':' .. tostring(name):lower()]
        if not item then return nil end
        local list = {}
        for _, stat in ipairs(item.stat_order) do
            local entry, range = item.stats[stat], RANGES[stat]
            local want = desired[entry.field.key]
            list[#list + 1] = { id = stat, game = entry.field.stock, current = want and want.value or entry.field.stock,
                                min = range.min, max = range.max, integer = range.integer,
                                editable = not entry.attachment, shared_with = #entry.field.users - 1 }
        end
        return list
    end,
    -- expression: '120', '150%', '+15', or nil to drop the override
    set = function(category, name, stat, expression)
        overrides[tostring(category):lower() .. ':' .. tostring(name):lower() .. ':' .. tostring(stat):lower()] =
            expression ~= nil and tostring(expression) or nil
        request_reload()
    end,
    reload = request_reload,
    verdict = function() return state.verdict end,
}

-- ---------------------------------------------------------------- startup
log(MOD.title .. ' v' .. MOD.version)
local api_ok, api_failure = pcall(function()
    assert(ffi_ok and ffi, 'LuaJIT FFI is unavailable')
    assert(ffi.abi('64bit'), 'Windows x64 is required')
    A = build_api()
end)
if not api_ok then A = nil end
local ok, failure = pcall(function()
    local loader = rawget(_G, 'CowboyBingusModLoader')
    if type(loader) == 'table' and tonumber(loader.api) and tonumber(loader.api) < 1 then
        error('Bingus Shared Loader is too old (API ' .. tostring(loader.api) .. '); v15 or newer is required', 0)
    end
    if not api_ok then error(tostring(api_failure), 0) end
    -- decoder and encoder must agree on known bit patterns before anything may be written
    for _, case in ipairs({ { 0x3F800000, 1.0 }, { 0x43AF0000, 350.0 }, { 0x42C80000, 100.0 },
                            { 0x3E800000, 0.25 }, { 0xBF000000, -0.5 }, { 0x44610000, 900.0 } }) do
        if bits_to_f32(case[1]) ~= case[2] or A.f32_bits(case[2]) ~= case[1] then
            error('float self-test failed', 0)
        end
    end
    if type(rawget(_G, 'update')) ~= 'function' then error('the game update hook is unavailable', 0) end
end)

if not ok then
    state.phase, state.failure = 'gave_up', tostring(failure)
    log('startup failed: ' .. tostring(failure))
    print('[' .. MOD.global .. '] ' .. tostring(failure))
    write_file(MOD.status, 'FAILED - ' .. tostring(failure) .. '\r\n' .. MOD.title .. ' v' .. MOD.version .. '\r\n')
    flush_log()
    return
end

log('armed; folder ' .. tostring(ensure_out_dir()))
write_file(MOD.status, 'WAITING - starting (nothing written yet)\r\n' .. MOD.title .. ' v' .. MOD.version .. '\r\n')
flush_log()

-- Guarded hook: we never cut other addons out of the update chain.
local original_update = update
local my_update
my_update = function(...)
    if not state.retired then
        local tick_ok, why = pcall(tick)
        if not tick_ok then
            state.errors = state.errors + 1
            log('tick: ' .. tostring(why))
            if state.errors >= 20 then state.retired = true end
        end
    end
    return original_update(...)
end
update = my_update
